"""
phase_fc

Autogenerated DPF operator classes.
"""

from __future__ import annotations
from typing import TYPE_CHECKING

from warnings import warn
from ansys.dpf.core.dpf_operator import Operator
from ansys.dpf.core.inputs import Input, _Inputs
from ansys.dpf.core.outputs import Output, _Outputs
from ansys.dpf.core.operators.specification import PinSpecification, Specification
from ansys.dpf.core.config import Config
from ansys.dpf.core.server_types import AnyServerType

if TYPE_CHECKING:
    from ansys.dpf.core.fields_container import FieldsContainer


class phase_fc(Operator):
    r"""Computes the
    `argument <https://en.wikipedia.org/wiki/Argument_(complex_analysis)>`__
    (phase angle) :math:`\mathrm{atan2}(\mathrm{Im}[i],\, \mathrm{Re}[i])`
    in radians for each complex-valued field pair in the input fields
    container, where pairs are matched by complex label. If no imaginary
    part is found for a real field, a zero-valued field is produced.


    Inputs
    ------
    fields_container: FieldsContainer
        Complex-valued fields container with paired real (complex label 0) and imaginary (complex label 1) fields.

    Outputs
    -------
    fields_container: FieldsContainer
        Fields container with phase angle fields $\mathrm{atan2}(\mathrm{Im}[i],\, \mathrm{Re}[i])$ in radians; zero-valued fields are produced where no imaginary part is found.

    Examples
    --------
    >>> from ansys.dpf import core as dpf

    >>> # Instantiate operator
    >>> op = dpf.operators.math.phase_fc()

    >>> # Make input connections
    >>> my_fields_container = dpf.FieldsContainer()
    >>> op.inputs.fields_container.connect(my_fields_container)

    >>> # Instantiate operator and connect inputs in one line
    >>> op = dpf.operators.math.phase_fc(
    ...     fields_container=my_fields_container,
    ... )

    >>> # Get output data
    >>> result_fields_container = op.outputs.fields_container()
    """

    def __init__(self, fields_container=None, config=None, server=None):
        super().__init__(
            name="phase_fc",
            config=config,
            server=server,
            inputs_type=InputsPhaseFc,
            outputs_type=OutputsPhaseFc,
        )
        if fields_container is not None:
            self.inputs.fields_container.connect(fields_container)

    @staticmethod
    def _spec() -> Specification:
        description = r"""Computes the
`argument <https://en.wikipedia.org/wiki/Argument_(complex_analysis)>`__
(phase angle) :math:`\mathrm{atan2}(\mathrm{Im}[i],\, \mathrm{Re}[i])`
in radians for each complex-valued field pair in the input fields
container, where pairs are matched by complex label. If no imaginary
part is found for a real field, a zero-valued field is produced.
"""
        spec = Specification(
            description=description,
            map_input_pin_spec={
                0: PinSpecification(
                    name="fields_container",
                    type_names=["fields_container"],
                    optional=False,
                    document=r"""Complex-valued fields container with paired real (complex label 0) and imaginary (complex label 1) fields.""",
                ),
            },
            map_output_pin_spec={
                0: PinSpecification(
                    name="fields_container",
                    type_names=["fields_container"],
                    optional=False,
                    document=r"""Fields container with phase angle fields $\mathrm{atan2}(\mathrm{Im}[i],\, \mathrm{Re}[i])$ in radians; zero-valued fields are produced where no imaginary part is found.""",
                ),
            },
        )
        return spec

    @staticmethod
    def default_config(server: AnyServerType = None) -> Config:
        """Returns the default config of the operator.

        This config can then be changed to the user needs and be used to
        instantiate the operator. The Configuration allows to customize
        how the operation will be processed by the operator.

        Parameters
        ----------
        server:
            Server with channel connected to the remote or local instance. When
            ``None``, attempts to use the global server.

        Returns
        -------
        config:
            A new Config instance equivalent to the default config for this operator.
        """
        return Operator.default_config(name="phase_fc", server=server)

    @property
    def inputs(self) -> InputsPhaseFc:
        """Enables to connect inputs to the operator

        Returns
        --------
        inputs:
            An instance of InputsPhaseFc.
        """
        return self._inputs

    @property
    def outputs(self) -> OutputsPhaseFc:
        """Enables to get outputs of the operator by evaluating it

        Returns
        --------
        outputs:
            An instance of OutputsPhaseFc.
        """
        return self._outputs


class InputsPhaseFc(_Inputs):
    """Intermediate class used to connect user inputs to
    phase_fc operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.math.phase_fc()
    >>> my_fields_container = dpf.FieldsContainer()
    >>> op.inputs.fields_container.connect(my_fields_container)
    """

    def __init__(self, op: Operator):
        super().__init__(phase_fc._spec().inputs, op)
        self._fields_container: Input[FieldsContainer] = Input(
            phase_fc._spec().input_pin(0), 0, op, -1
        )
        self._inputs.append(self._fields_container)

    @property
    def fields_container(self) -> Input[FieldsContainer]:
        r"""Allows to connect fields_container input to the operator.

        Complex-valued fields container with paired real (complex label 0) and imaginary (complex label 1) fields.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.phase_fc()
        >>> op.inputs.fields_container.connect(my_fields_container)
        >>> # or
        >>> op.inputs.fields_container(my_fields_container)
        """
        return self._fields_container


class OutputsPhaseFc(_Outputs):
    """Intermediate class used to get outputs from
    phase_fc operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.math.phase_fc()
    >>> # Connect inputs : op.inputs. ...
    >>> result_fields_container = op.outputs.fields_container()
    """

    def __init__(self, op: Operator):
        super().__init__(phase_fc._spec().outputs, op)
        self._fields_container: Output[FieldsContainer] = Output(
            phase_fc._spec().output_pin(0), 0, op
        )
        self._outputs.append(self._fields_container)

    @property
    def fields_container(self) -> Output[FieldsContainer]:
        r"""Allows to get fields_container output of the operator

        Fields container with phase angle fields $\mathrm{atan2}(\mathrm{Im}[i],\, \mathrm{Re}[i])$ in radians; zero-valued fields are produced where no imaginary part is found.

        Returns
        -------
        output:
            An Output instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.phase_fc()
        >>> # Get the output from op.outputs. ...
        >>> result_fields_container = op.outputs.fields_container()
        """
        return self._fields_container
