"""
real_part

Autogenerated DPF operator classes.
"""

from __future__ import annotations
from typing import TYPE_CHECKING

from warnings import warn
from ansys.dpf.core.dpf_operator import Operator
from ansys.dpf.core.inputs import Input, _Inputs
from ansys.dpf.core.outputs import Output, _Outputs
from ansys.dpf.core.operators.specification import PinSpecification, Specification
from ansys.dpf.core.config import Config
from ansys.dpf.core.server_types import AnyServerType

if TYPE_CHECKING:
    from ansys.dpf.core.fields_container import FieldsContainer


class real_part(Operator):
    r"""Extracts the real-part fields (complex label 0) from a complex-valued
    fields container. The output container preserves all labels except the
    complex label.


    Inputs
    ------
    fields_container: FieldsContainer
        Complex-valued fields container with real (complex label 0) and imaginary (complex label 1) part fields.

    Outputs
    -------
    fields_container: FieldsContainer
        Fields container containing only the real-part fields, without the complex label.

    Examples
    --------
    >>> from ansys.dpf import core as dpf

    >>> # Instantiate operator
    >>> op = dpf.operators.math.real_part()

    >>> # Make input connections
    >>> my_fields_container = dpf.FieldsContainer()
    >>> op.inputs.fields_container.connect(my_fields_container)

    >>> # Instantiate operator and connect inputs in one line
    >>> op = dpf.operators.math.real_part(
    ...     fields_container=my_fields_container,
    ... )

    >>> # Get output data
    >>> result_fields_container = op.outputs.fields_container()
    """

    def __init__(self, fields_container=None, config=None, server=None):
        super().__init__(
            name="realP_part",
            config=config,
            server=server,
            inputs_type=InputsRealPart,
            outputs_type=OutputsRealPart,
        )
        if fields_container is not None:
            self.inputs.fields_container.connect(fields_container)

    @staticmethod
    def _spec() -> Specification:
        description = r"""Extracts the real-part fields (complex label 0) from a complex-valued
fields container. The output container preserves all labels except the
complex label.
"""
        spec = Specification(
            description=description,
            map_input_pin_spec={
                0: PinSpecification(
                    name="fields_container",
                    type_names=["fields_container"],
                    optional=False,
                    document=r"""Complex-valued fields container with real (complex label 0) and imaginary (complex label 1) part fields.""",
                ),
            },
            map_output_pin_spec={
                0: PinSpecification(
                    name="fields_container",
                    type_names=["fields_container"],
                    optional=False,
                    document=r"""Fields container containing only the real-part fields, without the complex label.""",
                ),
            },
        )
        return spec

    @staticmethod
    def default_config(server: AnyServerType = None) -> Config:
        """Returns the default config of the operator.

        This config can then be changed to the user needs and be used to
        instantiate the operator. The Configuration allows to customize
        how the operation will be processed by the operator.

        Parameters
        ----------
        server:
            Server with channel connected to the remote or local instance. When
            ``None``, attempts to use the global server.

        Returns
        -------
        config:
            A new Config instance equivalent to the default config for this operator.
        """
        return Operator.default_config(name="realP_part", server=server)

    @property
    def inputs(self) -> InputsRealPart:
        """Enables to connect inputs to the operator

        Returns
        --------
        inputs:
            An instance of InputsRealPart.
        """
        return self._inputs

    @property
    def outputs(self) -> OutputsRealPart:
        """Enables to get outputs of the operator by evaluating it

        Returns
        --------
        outputs:
            An instance of OutputsRealPart.
        """
        return self._outputs


class InputsRealPart(_Inputs):
    """Intermediate class used to connect user inputs to
    real_part operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.math.real_part()
    >>> my_fields_container = dpf.FieldsContainer()
    >>> op.inputs.fields_container.connect(my_fields_container)
    """

    def __init__(self, op: Operator):
        super().__init__(real_part._spec().inputs, op)
        self._fields_container: Input[FieldsContainer] = Input(
            real_part._spec().input_pin(0), 0, op, -1
        )
        self._inputs.append(self._fields_container)

    @property
    def fields_container(self) -> Input[FieldsContainer]:
        r"""Allows to connect fields_container input to the operator.

        Complex-valued fields container with real (complex label 0) and imaginary (complex label 1) part fields.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.real_part()
        >>> op.inputs.fields_container.connect(my_fields_container)
        >>> # or
        >>> op.inputs.fields_container(my_fields_container)
        """
        return self._fields_container


class OutputsRealPart(_Outputs):
    """Intermediate class used to get outputs from
    real_part operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.math.real_part()
    >>> # Connect inputs : op.inputs. ...
    >>> result_fields_container = op.outputs.fields_container()
    """

    def __init__(self, op: Operator):
        super().__init__(real_part._spec().outputs, op)
        self._fields_container: Output[FieldsContainer] = Output(
            real_part._spec().output_pin(0), 0, op
        )
        self._outputs.append(self._fields_container)

    @property
    def fields_container(self) -> Output[FieldsContainer]:
        r"""Allows to get fields_container output of the operator

        Fields container containing only the real-part fields, without the complex label.

        Returns
        -------
        output:
            An Output instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.real_part()
        >>> # Get the output from op.outputs. ...
        >>> result_fields_container = op.outputs.fields_container()
        """
        return self._fields_container
