"""
time_integration

Autogenerated DPF operator classes.
"""

from __future__ import annotations
from typing import TYPE_CHECKING

from warnings import warn
from ansys.dpf.core.dpf_operator import Operator
from ansys.dpf.core.inputs import Input, _Inputs
from ansys.dpf.core.outputs import Output, _Outputs
from ansys.dpf.core.operators.specification import PinSpecification, Specification
from ansys.dpf.core.config import Config
from ansys.dpf.core.server_types import AnyServerType

if TYPE_CHECKING:
    from ansys.dpf.core.field import Field


class time_integration(Operator):
    r"""Computes the cumulative
    `integral <https://en.wikipedia.org/wiki/Integral>`__ of a scalar
    time-varying field using adaptive numerical integration. The input field
    must have a time-frequency support that provides the time values.

    When ``resample_output`` (pin 1) is true, the output time steps are
    resampled by the integrator (producing a new time support); when false,
    the output reuses the input time support. The optional integration
    constant (pin 4) is added to all output values as an initial condition.


    Inputs
    ------
    field: Field
        Scalar time-varying field to integrate. Must have a time-frequency support.
    resample_output: bool, optional
        When true, the output is resampled to an adaptively chosen set of time steps. When false (default), the output uses the same time support as the input.
    absolute_error: float, optional
        Absolute error tolerance for the resampling step. Only used when pin 1 is true.
    minimum_step_size: float, optional
        Minimum time step size allowed during resampling. Only used when pin 1 is true.
    integration_constant: float, optional
        Constant added to all integrated values as an initial condition. Default is $0$.

    Outputs
    -------
    field: Field
        Integrated scalar field. Has the same unit as (input unit $\times$ second). The time support is either the input support (when pin 1 is false) or a resampled support (when pin 1 is true).

    Examples
    --------
    >>> from ansys.dpf import core as dpf

    >>> # Instantiate operator
    >>> op = dpf.operators.math.time_integration()

    >>> # Make input connections
    >>> my_field = dpf.Field()
    >>> op.inputs.field.connect(my_field)
    >>> my_resample_output = bool()
    >>> op.inputs.resample_output.connect(my_resample_output)
    >>> my_absolute_error = float()
    >>> op.inputs.absolute_error.connect(my_absolute_error)
    >>> my_minimum_step_size = float()
    >>> op.inputs.minimum_step_size.connect(my_minimum_step_size)
    >>> my_integration_constant = float()
    >>> op.inputs.integration_constant.connect(my_integration_constant)

    >>> # Instantiate operator and connect inputs in one line
    >>> op = dpf.operators.math.time_integration(
    ...     field=my_field,
    ...     resample_output=my_resample_output,
    ...     absolute_error=my_absolute_error,
    ...     minimum_step_size=my_minimum_step_size,
    ...     integration_constant=my_integration_constant,
    ... )

    >>> # Get output data
    >>> result_field = op.outputs.field()
    """

    def __init__(
        self,
        field=None,
        resample_output=None,
        absolute_error=None,
        minimum_step_size=None,
        integration_constant=None,
        config=None,
        server=None,
    ):
        super().__init__(
            name="TimeIntegration",
            config=config,
            server=server,
            inputs_type=InputsTimeIntegration,
            outputs_type=OutputsTimeIntegration,
        )
        if field is not None:
            self.inputs.field.connect(field)
        if resample_output is not None:
            self.inputs.resample_output.connect(resample_output)
        if absolute_error is not None:
            self.inputs.absolute_error.connect(absolute_error)
        if minimum_step_size is not None:
            self.inputs.minimum_step_size.connect(minimum_step_size)
        if integration_constant is not None:
            self.inputs.integration_constant.connect(integration_constant)

    @staticmethod
    def _spec() -> Specification:
        description = r"""Computes the cumulative
`integral <https://en.wikipedia.org/wiki/Integral>`__ of a scalar
time-varying field using adaptive numerical integration. The input field
must have a time-frequency support that provides the time values.

When ``resample_output`` (pin 1) is true, the output time steps are
resampled by the integrator (producing a new time support); when false,
the output reuses the input time support. The optional integration
constant (pin 4) is added to all output values as an initial condition.
"""
        spec = Specification(
            description=description,
            map_input_pin_spec={
                0: PinSpecification(
                    name="field",
                    type_names=["field"],
                    optional=False,
                    document=r"""Scalar time-varying field to integrate. Must have a time-frequency support.""",
                ),
                1: PinSpecification(
                    name="resample_output",
                    type_names=["bool"],
                    optional=True,
                    document=r"""When true, the output is resampled to an adaptively chosen set of time steps. When false (default), the output uses the same time support as the input.""",
                ),
                2: PinSpecification(
                    name="absolute_error",
                    type_names=["double"],
                    optional=True,
                    document=r"""Absolute error tolerance for the resampling step. Only used when pin 1 is true.""",
                ),
                3: PinSpecification(
                    name="minimum_step_size",
                    type_names=["double"],
                    optional=True,
                    document=r"""Minimum time step size allowed during resampling. Only used when pin 1 is true.""",
                ),
                4: PinSpecification(
                    name="integration_constant",
                    type_names=["double"],
                    optional=True,
                    document=r"""Constant added to all integrated values as an initial condition. Default is $0$.""",
                ),
            },
            map_output_pin_spec={
                0: PinSpecification(
                    name="field",
                    type_names=["field"],
                    optional=False,
                    document=r"""Integrated scalar field. Has the same unit as (input unit $\times$ second). The time support is either the input support (when pin 1 is false) or a resampled support (when pin 1 is true).""",
                ),
            },
        )
        return spec

    @staticmethod
    def default_config(server: AnyServerType = None) -> Config:
        """Returns the default config of the operator.

        This config can then be changed to the user needs and be used to
        instantiate the operator. The Configuration allows to customize
        how the operation will be processed by the operator.

        Parameters
        ----------
        server:
            Server with channel connected to the remote or local instance. When
            ``None``, attempts to use the global server.

        Returns
        -------
        config:
            A new Config instance equivalent to the default config for this operator.
        """
        return Operator.default_config(name="TimeIntegration", server=server)

    @property
    def inputs(self) -> InputsTimeIntegration:
        """Enables to connect inputs to the operator

        Returns
        --------
        inputs:
            An instance of InputsTimeIntegration.
        """
        return self._inputs

    @property
    def outputs(self) -> OutputsTimeIntegration:
        """Enables to get outputs of the operator by evaluating it

        Returns
        --------
        outputs:
            An instance of OutputsTimeIntegration.
        """
        return self._outputs


class InputsTimeIntegration(_Inputs):
    """Intermediate class used to connect user inputs to
    time_integration operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.math.time_integration()
    >>> my_field = dpf.Field()
    >>> op.inputs.field.connect(my_field)
    >>> my_resample_output = bool()
    >>> op.inputs.resample_output.connect(my_resample_output)
    >>> my_absolute_error = float()
    >>> op.inputs.absolute_error.connect(my_absolute_error)
    >>> my_minimum_step_size = float()
    >>> op.inputs.minimum_step_size.connect(my_minimum_step_size)
    >>> my_integration_constant = float()
    >>> op.inputs.integration_constant.connect(my_integration_constant)
    """

    def __init__(self, op: Operator):
        super().__init__(time_integration._spec().inputs, op)
        self._field: Input[Field] = Input(
            time_integration._spec().input_pin(0), 0, op, -1
        )
        self._inputs.append(self._field)
        self._resample_output: Input[bool] = Input(
            time_integration._spec().input_pin(1), 1, op, -1
        )
        self._inputs.append(self._resample_output)
        self._absolute_error: Input[float] = Input(
            time_integration._spec().input_pin(2), 2, op, -1
        )
        self._inputs.append(self._absolute_error)
        self._minimum_step_size: Input[float] = Input(
            time_integration._spec().input_pin(3), 3, op, -1
        )
        self._inputs.append(self._minimum_step_size)
        self._integration_constant: Input[float] = Input(
            time_integration._spec().input_pin(4), 4, op, -1
        )
        self._inputs.append(self._integration_constant)

    @property
    def field(self) -> Input[Field]:
        r"""Allows to connect field input to the operator.

        Scalar time-varying field to integrate. Must have a time-frequency support.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.time_integration()
        >>> op.inputs.field.connect(my_field)
        >>> # or
        >>> op.inputs.field(my_field)
        """
        return self._field

    @property
    def resample_output(self) -> Input[bool]:
        r"""Allows to connect resample_output input to the operator.

        When true, the output is resampled to an adaptively chosen set of time steps. When false (default), the output uses the same time support as the input.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.time_integration()
        >>> op.inputs.resample_output.connect(my_resample_output)
        >>> # or
        >>> op.inputs.resample_output(my_resample_output)
        """
        return self._resample_output

    @property
    def absolute_error(self) -> Input[float]:
        r"""Allows to connect absolute_error input to the operator.

        Absolute error tolerance for the resampling step. Only used when pin 1 is true.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.time_integration()
        >>> op.inputs.absolute_error.connect(my_absolute_error)
        >>> # or
        >>> op.inputs.absolute_error(my_absolute_error)
        """
        return self._absolute_error

    @property
    def minimum_step_size(self) -> Input[float]:
        r"""Allows to connect minimum_step_size input to the operator.

        Minimum time step size allowed during resampling. Only used when pin 1 is true.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.time_integration()
        >>> op.inputs.minimum_step_size.connect(my_minimum_step_size)
        >>> # or
        >>> op.inputs.minimum_step_size(my_minimum_step_size)
        """
        return self._minimum_step_size

    @property
    def integration_constant(self) -> Input[float]:
        r"""Allows to connect integration_constant input to the operator.

        Constant added to all integrated values as an initial condition. Default is $0$.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.time_integration()
        >>> op.inputs.integration_constant.connect(my_integration_constant)
        >>> # or
        >>> op.inputs.integration_constant(my_integration_constant)
        """
        return self._integration_constant


class OutputsTimeIntegration(_Outputs):
    """Intermediate class used to get outputs from
    time_integration operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.math.time_integration()
    >>> # Connect inputs : op.inputs. ...
    >>> result_field = op.outputs.field()
    """

    def __init__(self, op: Operator):
        super().__init__(time_integration._spec().outputs, op)
        self._field: Output[Field] = Output(
            time_integration._spec().output_pin(0), 0, op
        )
        self._outputs.append(self._field)

    @property
    def field(self) -> Output[Field]:
        r"""Allows to get field output of the operator

        Integrated scalar field. Has the same unit as (input unit $\times$ second). The time support is either the input support (when pin 1 is false) or a resampled support (when pin 1 is true).

        Returns
        -------
        output:
            An Output instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.math.time_integration()
        >>> # Get the output from op.outputs. ...
        >>> result_field = op.outputs.field()
        """
        return self._field
