documentation:
  - changed-files:
    - any-glob-to-any-file:
      - doc/source/**/*
      - examples/**/*
maintenance:
  - changed-files:
    - any-glob-to-any-file:
      - .flake8
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md
      - codecov.yml
      - ignore_words.txt
      - setup.py
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - setup.py
      - requirements/*
CI/CD:
  - changed-files:
    - any-glob-to-any-file:
      - docker/**/*
      - .github/**/*
      - .ci/**/*