documentation:
  - changed-files:
    - any-glob-to-any-file:
      - doc/source/**/*
      - doc/sphinx_utilities/**/*
      - doc/styles/**/*
      - doc/*
examples:
  - changed-files:
    - any-glob-to-any-file:  
      - doc/sphinx_gallery_examples/**/*
tutorials:
  - changed-files:
    - any-glob-to-any-file:  
      - doc/sphinx_gallery_tutorials/**/*
maintenance:
  - changed-files:
    - any-glob-to-any-file:
      - .flake8
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md
      - codecov.yml
      - ignore_words.txt
      - setup.py
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - setup.py
      - requirements/*
CI/CD:
  - changed-files:
    - any-glob-to-any-file:
      - docker/**/*
      - .github/**/*
      - .ci/**/*