exclude: >
  (?x)^(
    doc/source/
    |src/ansys/dpf/core/operators/
    |examples_notebooks/
    |src/ansys/dpf/core/__init__.py
    |doc/styles/
    |src/ansys/dpf/gate/
    |src/ansys/dpf/gatebin/
    |src/ansys/grpc/dpf/
  )
repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.3
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: ["--ignore-words=./doc/styles/Vocab/ANSYS/accept.txt"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: requirements-txt-fixer

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.2
  hooks:
    - id: check-github-workflows
