"""
csharp_generator

Autogenerated DPF operator classes.
"""

from __future__ import annotations

from warnings import warn
from ansys.dpf.core.dpf_operator import Operator
from ansys.dpf.core.inputs import Input, _Inputs
from ansys.dpf.core.outputs import _Outputs
from ansys.dpf.core.operators.specification import PinSpecification, Specification
from ansys.dpf.core.config import Config
from ansys.dpf.core.server_types import AnyServerType


class csharp_generator(Operator):
    r"""Generates a C# wrapper file (.cs) containing a class for each public
    operator found in a loaded plugin DLL. The DLL is loaded using the given
    ``load_symbol`` and ``library_key``. All non-private operators
    discovered in the plugin are written to the single file at
    ``output_path``.

       **Note:** Operators whose exposure property is set to ``private`` are
       silently excluded from the generated output.

    Inputs & outputs of each operator are represented as typed
    ``LinkableInput<T>`` and ``LinkableOutput<T>`` properties on the
    generated class.


    Inputs
    ------
    dll_source_path: str
        Path to the plugin DLL to load.
    output_path: str
        Path where the .cs wrapper file will be written.
    load_symbol: str, optional
        Symbol name used to load operators from the DLL. Defaults to "LoadOperators".
    library_key: str
        Key used to identify the plugin library when loading.

    Outputs
    -------

    Examples
    --------
    >>> from ansys.dpf import core as dpf

    >>> # Instantiate operator
    >>> op = dpf.operators.utility.csharp_generator()

    >>> # Make input connections
    >>> my_dll_source_path = str()
    >>> op.inputs.dll_source_path.connect(my_dll_source_path)
    >>> my_output_path = str()
    >>> op.inputs.output_path.connect(my_output_path)
    >>> my_load_symbol = str()
    >>> op.inputs.load_symbol.connect(my_load_symbol)
    >>> my_library_key = str()
    >>> op.inputs.library_key.connect(my_library_key)

    >>> # Instantiate operator and connect inputs in one line
    >>> op = dpf.operators.utility.csharp_generator(
    ...     dll_source_path=my_dll_source_path,
    ...     output_path=my_output_path,
    ...     load_symbol=my_load_symbol,
    ...     library_key=my_library_key,
    ... )

    """

    def __init__(
        self,
        dll_source_path=None,
        output_path=None,
        load_symbol=None,
        library_key=None,
        config=None,
        server=None,
    ):
        super().__init__(
            name="csharp_generator",
            config=config,
            server=server,
            inputs_type=InputsCsharpGenerator,
            outputs_type=OutputsCsharpGenerator,
        )
        if dll_source_path is not None:
            self.inputs.dll_source_path.connect(dll_source_path)
        if output_path is not None:
            self.inputs.output_path.connect(output_path)
        if load_symbol is not None:
            self.inputs.load_symbol.connect(load_symbol)
        if library_key is not None:
            self.inputs.library_key.connect(library_key)

    @staticmethod
    def _spec() -> Specification:
        description = r"""Generates a C# wrapper file (.cs) containing a class for each public
operator found in a loaded plugin DLL. The DLL is loaded using the given
``load_symbol`` and ``library_key``. All non-private operators
discovered in the plugin are written to the single file at
``output_path``.

   **Note:** Operators whose exposure property is set to ``private`` are
   silently excluded from the generated output.

Inputs & outputs of each operator are represented as typed
``LinkableInput<T>`` and ``LinkableOutput<T>`` properties on the
generated class.
"""
        spec = Specification(
            description=description,
            map_input_pin_spec={
                0: PinSpecification(
                    name="dll_source_path",
                    type_names=["string"],
                    optional=False,
                    document=r"""Path to the plugin DLL to load.""",
                ),
                1: PinSpecification(
                    name="output_path",
                    type_names=["string"],
                    optional=False,
                    document=r"""Path where the .cs wrapper file will be written.""",
                ),
                2: PinSpecification(
                    name="load_symbol",
                    type_names=["string"],
                    optional=True,
                    document=r"""Symbol name used to load operators from the DLL. Defaults to "LoadOperators".""",
                ),
                3: PinSpecification(
                    name="library_key",
                    type_names=["string"],
                    optional=False,
                    document=r"""Key used to identify the plugin library when loading.""",
                ),
            },
            map_output_pin_spec={},
        )
        return spec

    @staticmethod
    def default_config(server: AnyServerType = None) -> Config:
        """Returns the default config of the operator.

        This config can then be changed to the user needs and be used to
        instantiate the operator. The Configuration allows to customize
        how the operation will be processed by the operator.

        Parameters
        ----------
        server:
            Server with channel connected to the remote or local instance. When
            ``None``, attempts to use the global server.

        Returns
        -------
        config:
            A new Config instance equivalent to the default config for this operator.
        """
        return Operator.default_config(name="csharp_generator", server=server)

    @property
    def inputs(self) -> InputsCsharpGenerator:
        """Enables to connect inputs to the operator

        Returns
        --------
        inputs:
            An instance of InputsCsharpGenerator.
        """
        return self._inputs

    @property
    def outputs(self) -> OutputsCsharpGenerator:
        """Enables to get outputs of the operator by evaluating it

        Returns
        --------
        outputs:
            An instance of OutputsCsharpGenerator.
        """
        return self._outputs


class InputsCsharpGenerator(_Inputs):
    """Intermediate class used to connect user inputs to
    csharp_generator operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.utility.csharp_generator()
    >>> my_dll_source_path = str()
    >>> op.inputs.dll_source_path.connect(my_dll_source_path)
    >>> my_output_path = str()
    >>> op.inputs.output_path.connect(my_output_path)
    >>> my_load_symbol = str()
    >>> op.inputs.load_symbol.connect(my_load_symbol)
    >>> my_library_key = str()
    >>> op.inputs.library_key.connect(my_library_key)
    """

    def __init__(self, op: Operator):
        super().__init__(csharp_generator._spec().inputs, op)
        self._dll_source_path: Input[str] = Input(
            csharp_generator._spec().input_pin(0), 0, op, -1
        )
        self._inputs.append(self._dll_source_path)
        self._output_path: Input[str] = Input(
            csharp_generator._spec().input_pin(1), 1, op, -1
        )
        self._inputs.append(self._output_path)
        self._load_symbol: Input[str] = Input(
            csharp_generator._spec().input_pin(2), 2, op, -1
        )
        self._inputs.append(self._load_symbol)
        self._library_key: Input[str] = Input(
            csharp_generator._spec().input_pin(3), 3, op, -1
        )
        self._inputs.append(self._library_key)

    @property
    def dll_source_path(self) -> Input[str]:
        r"""Allows to connect dll_source_path input to the operator.

        Path to the plugin DLL to load.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.csharp_generator()
        >>> op.inputs.dll_source_path.connect(my_dll_source_path)
        >>> # or
        >>> op.inputs.dll_source_path(my_dll_source_path)
        """
        return self._dll_source_path

    @property
    def output_path(self) -> Input[str]:
        r"""Allows to connect output_path input to the operator.

        Path where the .cs wrapper file will be written.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.csharp_generator()
        >>> op.inputs.output_path.connect(my_output_path)
        >>> # or
        >>> op.inputs.output_path(my_output_path)
        """
        return self._output_path

    @property
    def load_symbol(self) -> Input[str]:
        r"""Allows to connect load_symbol input to the operator.

        Symbol name used to load operators from the DLL. Defaults to "LoadOperators".

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.csharp_generator()
        >>> op.inputs.load_symbol.connect(my_load_symbol)
        >>> # or
        >>> op.inputs.load_symbol(my_load_symbol)
        """
        return self._load_symbol

    @property
    def library_key(self) -> Input[str]:
        r"""Allows to connect library_key input to the operator.

        Key used to identify the plugin library when loading.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.csharp_generator()
        >>> op.inputs.library_key.connect(my_library_key)
        >>> # or
        >>> op.inputs.library_key(my_library_key)
        """
        return self._library_key


class OutputsCsharpGenerator(_Outputs):
    """Intermediate class used to get outputs from
    csharp_generator operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.utility.csharp_generator()
    >>> # Connect inputs : op.inputs. ...
    """

    def __init__(self, op: Operator):
        super().__init__(csharp_generator._spec().outputs, op)
