"""
get_workflow_step_index_operator_statuses

Autogenerated DPF operator classes.
"""

from __future__ import annotations
from typing import TYPE_CHECKING

from warnings import warn
from ansys.dpf.core.dpf_operator import Operator
from ansys.dpf.core.inputs import Input, _Inputs
from ansys.dpf.core.outputs import Output, _Outputs
from ansys.dpf.core.operators.specification import PinSpecification, Specification
from ansys.dpf.core.config import Config
from ansys.dpf.core.server_types import AnyServerType

if TYPE_CHECKING:
    from ansys.dpf.core.generic_data_container import GenericDataContainer
    from ansys.dpf.core.workflow import Workflow


class get_workflow_step_index_operator_statuses(Operator):
    r"""Get the status of every operator tracked by the workflow’s step index.
    Returns a GenericDataContainer with keys ‘opName_opId’ and int values
    corresponding to E_OperatorState.


    Inputs
    ------
    workflow: Workflow

    Outputs
    -------
    operator_statuses: GenericDataContainer

    Examples
    --------
    >>> from ansys.dpf import core as dpf

    >>> # Instantiate operator
    >>> op = dpf.operators.utility.get_workflow_step_index_operator_statuses()

    >>> # Make input connections
    >>> my_workflow = dpf.Workflow()
    >>> op.inputs.workflow.connect(my_workflow)

    >>> # Instantiate operator and connect inputs in one line
    >>> op = dpf.operators.utility.get_workflow_step_index_operator_statuses(
    ...     workflow=my_workflow,
    ... )

    >>> # Get output data
    >>> result_operator_statuses = op.outputs.operator_statuses()
    """

    def __init__(self, workflow=None, config=None, server=None):
        super().__init__(
            name="workflow_step_index::operator_statuses",
            config=config,
            server=server,
            inputs_type=InputsGetWorkflowStepIndexOperatorStatuses,
            outputs_type=OutputsGetWorkflowStepIndexOperatorStatuses,
        )
        if workflow is not None:
            self.inputs.workflow.connect(workflow)

    @staticmethod
    def _spec() -> Specification:
        description = r"""Get the status of every operator tracked by the workflow’s step index.
Returns a GenericDataContainer with keys ‘opName_opId’ and int values
corresponding to E_OperatorState.
"""
        spec = Specification(
            description=description,
            map_input_pin_spec={
                0: PinSpecification(
                    name="workflow",
                    type_names=["workflow"],
                    optional=False,
                    document=r"""""",
                ),
            },
            map_output_pin_spec={
                0: PinSpecification(
                    name="operator_statuses",
                    type_names=["generic_data_container"],
                    optional=False,
                    document=r"""""",
                ),
            },
        )
        return spec

    @staticmethod
    def default_config(server: AnyServerType = None) -> Config:
        """Returns the default config of the operator.

        This config can then be changed to the user needs and be used to
        instantiate the operator. The Configuration allows to customize
        how the operation will be processed by the operator.

        Parameters
        ----------
        server:
            Server with channel connected to the remote or local instance. When
            ``None``, attempts to use the global server.

        Returns
        -------
        config:
            A new Config instance equivalent to the default config for this operator.
        """
        return Operator.default_config(
            name="workflow_step_index::operator_statuses", server=server
        )

    @property
    def inputs(self) -> InputsGetWorkflowStepIndexOperatorStatuses:
        """Enables to connect inputs to the operator

        Returns
        --------
        inputs:
            An instance of InputsGetWorkflowStepIndexOperatorStatuses.
        """
        return self._inputs

    @property
    def outputs(self) -> OutputsGetWorkflowStepIndexOperatorStatuses:
        """Enables to get outputs of the operator by evaluating it

        Returns
        --------
        outputs:
            An instance of OutputsGetWorkflowStepIndexOperatorStatuses.
        """
        return self._outputs


class InputsGetWorkflowStepIndexOperatorStatuses(_Inputs):
    """Intermediate class used to connect user inputs to
    get_workflow_step_index_operator_statuses operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.utility.get_workflow_step_index_operator_statuses()
    >>> my_workflow = dpf.Workflow()
    >>> op.inputs.workflow.connect(my_workflow)
    """

    def __init__(self, op: Operator):
        super().__init__(get_workflow_step_index_operator_statuses._spec().inputs, op)
        self._workflow: Input[Workflow] = Input(
            get_workflow_step_index_operator_statuses._spec().input_pin(0), 0, op, -1
        )
        self._inputs.append(self._workflow)

    @property
    def workflow(self) -> Input[Workflow]:
        r"""Allows to connect workflow input to the operator.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.get_workflow_step_index_operator_statuses()
        >>> op.inputs.workflow.connect(my_workflow)
        >>> # or
        >>> op.inputs.workflow(my_workflow)
        """
        return self._workflow


class OutputsGetWorkflowStepIndexOperatorStatuses(_Outputs):
    """Intermediate class used to get outputs from
    get_workflow_step_index_operator_statuses operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.utility.get_workflow_step_index_operator_statuses()
    >>> # Connect inputs : op.inputs. ...
    >>> result_operator_statuses = op.outputs.operator_statuses()
    """

    def __init__(self, op: Operator):
        super().__init__(get_workflow_step_index_operator_statuses._spec().outputs, op)
        self._operator_statuses: Output[GenericDataContainer] = Output(
            get_workflow_step_index_operator_statuses._spec().output_pin(0), 0, op
        )
        self._outputs.append(self._operator_statuses)

    @property
    def operator_statuses(self) -> Output[GenericDataContainer]:
        r"""Allows to get operator_statuses output of the operator

        Returns
        -------
        output:
            An Output instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.get_workflow_step_index_operator_statuses()
        >>> # Get the output from op.outputs. ...
        >>> result_operator_statuses = op.outputs.operator_statuses()
        """
        return self._operator_statuses
