"""
transpose_fields_container

Autogenerated DPF operator classes.
"""

from __future__ import annotations
from typing import TYPE_CHECKING

from warnings import warn
from ansys.dpf.core.dpf_operator import Operator
from ansys.dpf.core.inputs import Input, _Inputs
from ansys.dpf.core.outputs import Output, _Outputs
from ansys.dpf.core.operators.specification import PinSpecification, Specification
from ansys.dpf.core.config import Config
from ansys.dpf.core.server_types import AnyServerType

if TYPE_CHECKING:
    from ansys.dpf.core.fields_container import FieldsContainer


class transpose_fields_container(Operator):
    r"""Transposes a fields container so that the fields’ scoping becomes the
    container’s scoping and a chosen label (default: time) becomes the
    fields’ scoping.

    Input layout (example with time label, 2 body labels, 3 nodes): FC
    labels: [time, body] Field 0: {time:1, body:1} -> scoping {n1, n2, n3},
    data […] Field 1: {time:1, body:2} -> scoping {n4, n5}, data […] Field
    2: {time:2, body:1} -> scoping {n1, n2, n3}, data […] Field 3: {time:2,
    body:2} -> scoping {n4, n5}, data […]

    Output layout (transposed on time): FC labels: [Nodal, body] Field 0:
    {Nodal:n1, body:1} -> scoping {t1, t2}, data [gathered from fields 0,2]
    Field 1: {Nodal:n2, body:1} -> scoping {t1, t2}, data [gathered from
    fields 0,2] Field 1: {Nodal:n3, body:1} -> scoping {t1, t2}, data
    [gathered from fields 0,2] Field 2: {Nodal:n4, body:2} -> scoping {t1,
    t2}, data [gathered from fields 1,3] Field 3: {Nodal:n5, body:2} ->
    scoping {t1, t2}, data [gathered from fields 1,3] …

    Each output field gathers one entity’s data across all values of the
    transposed label from the input fields that share the same
    non-transposed labels. All input fields sharing a labelspace where only
    the transposed label changes must have the same scoping and location.


    Inputs
    ------
    fields_container: FieldsContainer
        It is assumed that the fields container consists of fields having the same scoping.
    label: str, optional
        fields container label to use as fields label (default is time)

    Outputs
    -------
    fields_container: FieldsContainer

    Examples
    --------
    >>> from ansys.dpf import core as dpf

    >>> # Instantiate operator
    >>> op = dpf.operators.utility.transpose_fields_container()

    >>> # Make input connections
    >>> my_fields_container = dpf.FieldsContainer()
    >>> op.inputs.fields_container.connect(my_fields_container)
    >>> my_label = str()
    >>> op.inputs.label.connect(my_label)

    >>> # Instantiate operator and connect inputs in one line
    >>> op = dpf.operators.utility.transpose_fields_container(
    ...     fields_container=my_fields_container,
    ...     label=my_label,
    ... )

    >>> # Get output data
    >>> result_fields_container = op.outputs.fields_container()
    """

    def __init__(self, fields_container=None, label=None, config=None, server=None):
        super().__init__(
            name="transpose_fields_container",
            config=config,
            server=server,
            inputs_type=InputsTransposeFieldsContainer,
            outputs_type=OutputsTransposeFieldsContainer,
        )
        if fields_container is not None:
            self.inputs.fields_container.connect(fields_container)
        if label is not None:
            self.inputs.label.connect(label)

    @staticmethod
    def _spec() -> Specification:
        description = r"""Transposes a fields container so that the fields’ scoping becomes the
container’s scoping and a chosen label (default: time) becomes the
fields’ scoping.

Input layout (example with time label, 2 body labels, 3 nodes): FC
labels: [time, body] Field 0: {time:1, body:1} -> scoping {n1, n2, n3},
data […] Field 1: {time:1, body:2} -> scoping {n4, n5}, data […] Field
2: {time:2, body:1} -> scoping {n1, n2, n3}, data […] Field 3: {time:2,
body:2} -> scoping {n4, n5}, data […]

Output layout (transposed on time): FC labels: [Nodal, body] Field 0:
{Nodal:n1, body:1} -> scoping {t1, t2}, data [gathered from fields 0,2]
Field 1: {Nodal:n2, body:1} -> scoping {t1, t2}, data [gathered from
fields 0,2] Field 1: {Nodal:n3, body:1} -> scoping {t1, t2}, data
[gathered from fields 0,2] Field 2: {Nodal:n4, body:2} -> scoping {t1,
t2}, data [gathered from fields 1,3] Field 3: {Nodal:n5, body:2} ->
scoping {t1, t2}, data [gathered from fields 1,3] …

Each output field gathers one entity’s data across all values of the
transposed label from the input fields that share the same
non-transposed labels. All input fields sharing a labelspace where only
the transposed label changes must have the same scoping and location.
"""
        spec = Specification(
            description=description,
            map_input_pin_spec={
                0: PinSpecification(
                    name="fields_container",
                    type_names=["fields_container"],
                    optional=False,
                    document=r"""It is assumed that the fields container consists of fields having the same scoping.""",
                ),
                1: PinSpecification(
                    name="label",
                    type_names=["string"],
                    optional=True,
                    document=r"""fields container label to use as fields label (default is time)""",
                ),
            },
            map_output_pin_spec={
                0: PinSpecification(
                    name="fields_container",
                    type_names=["fields_container"],
                    optional=False,
                    document=r"""""",
                ),
            },
        )
        return spec

    @staticmethod
    def default_config(server: AnyServerType = None) -> Config:
        """Returns the default config of the operator.

        This config can then be changed to the user needs and be used to
        instantiate the operator. The Configuration allows to customize
        how the operation will be processed by the operator.

        Parameters
        ----------
        server:
            Server with channel connected to the remote or local instance. When
            ``None``, attempts to use the global server.

        Returns
        -------
        config:
            A new Config instance equivalent to the default config for this operator.
        """
        return Operator.default_config(name="transpose_fields_container", server=server)

    @property
    def inputs(self) -> InputsTransposeFieldsContainer:
        """Enables to connect inputs to the operator

        Returns
        --------
        inputs:
            An instance of InputsTransposeFieldsContainer.
        """
        return self._inputs

    @property
    def outputs(self) -> OutputsTransposeFieldsContainer:
        """Enables to get outputs of the operator by evaluating it

        Returns
        --------
        outputs:
            An instance of OutputsTransposeFieldsContainer.
        """
        return self._outputs


class InputsTransposeFieldsContainer(_Inputs):
    """Intermediate class used to connect user inputs to
    transpose_fields_container operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.utility.transpose_fields_container()
    >>> my_fields_container = dpf.FieldsContainer()
    >>> op.inputs.fields_container.connect(my_fields_container)
    >>> my_label = str()
    >>> op.inputs.label.connect(my_label)
    """

    def __init__(self, op: Operator):
        super().__init__(transpose_fields_container._spec().inputs, op)
        self._fields_container: Input[FieldsContainer] = Input(
            transpose_fields_container._spec().input_pin(0), 0, op, -1
        )
        self._inputs.append(self._fields_container)
        self._label: Input[str] = Input(
            transpose_fields_container._spec().input_pin(1), 1, op, -1
        )
        self._inputs.append(self._label)

    @property
    def fields_container(self) -> Input[FieldsContainer]:
        r"""Allows to connect fields_container input to the operator.

        It is assumed that the fields container consists of fields having the same scoping.

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.transpose_fields_container()
        >>> op.inputs.fields_container.connect(my_fields_container)
        >>> # or
        >>> op.inputs.fields_container(my_fields_container)
        """
        return self._fields_container

    @property
    def label(self) -> Input[str]:
        r"""Allows to connect label input to the operator.

        fields container label to use as fields label (default is time)

        Returns
        -------
        input:
            An Input instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.transpose_fields_container()
        >>> op.inputs.label.connect(my_label)
        >>> # or
        >>> op.inputs.label(my_label)
        """
        return self._label


class OutputsTransposeFieldsContainer(_Outputs):
    """Intermediate class used to get outputs from
    transpose_fields_container operator.

    Examples
    --------
    >>> from ansys.dpf import core as dpf
    >>> op = dpf.operators.utility.transpose_fields_container()
    >>> # Connect inputs : op.inputs. ...
    >>> result_fields_container = op.outputs.fields_container()
    """

    def __init__(self, op: Operator):
        super().__init__(transpose_fields_container._spec().outputs, op)
        self._fields_container: Output[FieldsContainer] = Output(
            transpose_fields_container._spec().output_pin(0), 0, op
        )
        self._outputs.append(self._fields_container)

    @property
    def fields_container(self) -> Output[FieldsContainer]:
        r"""Allows to get fields_container output of the operator

        Returns
        -------
        output:
            An Output instance for this pin.

        Examples
        --------
        >>> from ansys.dpf import core as dpf
        >>> op = dpf.operators.utility.transpose_fields_container()
        >>> # Get the output from op.outputs. ...
        >>> result_fields_container = op.outputs.fields_container()
        """
        return self._fields_container
