name: 🐞 Bug, problem, error
description: Fill a bug report here
title: "Bug located in ..."
labels: ["bug"]
assignees: [""]

body:

  - type: markdown
    attributes:
      value: '# 🐞 **Problem**'

  - type: checkboxes
    id: new-bug
    attributes:
      label: Before submitting the issue
      description: Please, make sure the following conditions are met
      options:
      - label: I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
        required: true
      - label: I have searched among the existing issues
        required: true
      - label: I am using a Python virtual environment
        required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      placeholder: Describe what bug you encountered and what should have happened
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      placeholder: Please write the steps in a list form
    validations:
      required: true

  - type: markdown
    attributes:
      value: '# 🖥️ **System Information**'

  - type: dropdown
    id: os-name
    attributes:
      label: Which Operating System causes the issue?
      multiple: true
      options:
       - 'Windows'
       - 'MacOS'
       - 'Linux'
    validations:
      required: true
   
  - type: dropdown
    id: dpf-server-version
    attributes:
      label: Which DPF/Ansys version are you using?
      multiple: false
      options:
       - 'Ansys 2024 R1'
       - 'Ansys 2023 R2'
       - 'DPF Server 2023.2.pre1'
       - 'DPF Server 2023.2.pre0'
       - 'Ansys 2023 R1'
       - 'Ansys 2022 R2'
       - 'Ansys 2022 R1'
       - 'Ansys 2021 R2'
       - 'Ansys 2021 R1'
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Which Python version causes the issue?
      description: Run `python --version` to verify your Python version
      multiple: true
      options:
       - '3.7'
       - '3.8'
       - '3.9'
       - '3.10'
       - '3.11'
    validations:
      required: true

  - type: textarea
    id: installed-packages
    attributes:
      label: Installed packages
      description: Run `python -m pip list` to list installed packages
      placeholder: Paste the output of `python -m pip list` here
    validations:
      required: true
