operators = {
    "amplitude_fc": {"category": "math", "short_name": "amplitude_fc"},
    "mesh_support_provider": {
        "category": "metadata",
        "short_name": "mesh_support_provider",
    },
    "nodal_fraction_fc": {"category": "averaging", "short_name": "nodal_fraction_fc"},
    "cyclic_expansion": {"category": "result", "short_name": "cyclic_expansion"},
    "topology::mass": {"category": "geo", "short_name": "mass"},
    "unit_convert_fc": {"category": "math", "short_name": "unit_convert_fc"},
    "minus": {"category": "math", "short_name": "minus"},
    "EPPL1": {"category": "result", "short_name": "plastic_strain_principal_1"},
    "cplx_multiply": {"category": "math", "short_name": "cplx_multiply"},
    "unit_convert": {"category": "math", "short_name": "unit_convert"},
    "accumulate_min_over_label_fc": {
        "category": "math",
        "short_name": "accumulate_min_over_label_fc",
    },
    "grpc_server_shutdown": {"category": "other", "short_name": "grpc_server_shutdown"},
    "add": {"category": "math", "short_name": "add"},
    "min_max_by_time": {"category": "min_max", "short_name": "min_max_by_time"},
    "add_fc": {"category": "math", "short_name": "add_fc"},
    "phase_of_max": {"category": "min_max", "short_name": "phase_of_max"},
    "sin_fc": {"category": "math", "short_name": "sin_fc"},
    "add_constant": {"category": "math", "short_name": "add_constant"},
    "add_constant_fc": {"category": "math", "short_name": "add_constant_fc"},
    "accumulate": {"category": "math", "short_name": "accumulate"},
    "minus_fc": {"category": "math", "short_name": "minus_fc"},
    "Pow": {"category": "math", "short_name": "pow"},
    "scoping::intersect": {"category": "scoping", "short_name": "intersect"},
    "GetElementScopingFromMesh": {
        "category": "scoping",
        "short_name": "elemental_from_mesh",
    },
    "scale": {"category": "math", "short_name": "scale"},
    "Pow_fc": {"category": "math", "short_name": "pow_fc"},
    "scale_fc": {"category": "math", "short_name": "scale_fc"},
    "sweeping_phase": {"category": "math", "short_name": "sweeping_phase"},
    "centroid": {"category": "math", "short_name": "centroid"},
    "sweeping_phase_fc": {"category": "math", "short_name": "sweeping_phase_fc"},
    "centroid_fc": {"category": "math", "short_name": "centroid_fc"},
    "sqr": {"category": "math", "short_name": "sqr"},
    "elemental_fraction_fc": {
        "category": "averaging",
        "short_name": "elemental_fraction_fc",
    },
    "sin": {"category": "math", "short_name": "sin"},
    "cos": {"category": "math", "short_name": "cos"},
    "RigidTransformationProvider": {
        "category": "result",
        "short_name": "rigid_transformation",
    },
    "InjectToFieldContainer": {"category": "utility", "short_name": "field_to_fc"},
    "cos_fc": {"category": "math", "short_name": "cos_fc"},
    "CplxOp": {"category": "math", "short_name": "linear_combination"},
    "sqr_fc": {"category": "math", "short_name": "sqr_fc"},
    "sqrt": {"category": "math", "short_name": "sqrt"},
    "norm": {"category": "math", "short_name": "norm"},
    "time_of_max_by_entity": {
        "category": "min_max",
        "short_name": "time_of_max_by_entity",
    },
    "sqrt_fc": {"category": "math", "short_name": "sqrt_fc"},
    "norm_fc": {"category": "math", "short_name": "norm_fc"},
    "component_wise_divide": {
        "category": "math",
        "short_name": "component_wise_divide",
    },
    "component_wise_divide_fc": {
        "category": "math",
        "short_name": "component_wise_divide_fc",
    },
    "kronecker_prod": {"category": "math", "short_name": "kronecker_prod"},
    "html_doc": {"category": "utility", "short_name": "html_doc"},
    "realP_part": {"category": "math", "short_name": "real_part"},
    "conjugate": {"category": "math", "short_name": "conjugate"},
    "mapdl::rst::NPEL": {
        "category": "result",
        "short_name": "nodal_averaged_elastic_strains",
    },
    "img_part": {"category": "math", "short_name": "img_part"},
    "amplitude": {"category": "math", "short_name": "amplitude"},
    "cplx_add": {"category": "math", "short_name": "cplx_add"},
    "cplx_dot": {"category": "math", "short_name": "cplx_dot"},
    "cplx_divide": {"category": "math", "short_name": "cplx_divide"},
    "make_unit": {"category": "utility", "short_name": "unitary_field"},
    "dot": {"category": "math", "short_name": "dot"},
    "EPELY": {"category": "result", "short_name": "elastic_strain_Y"},
    "cplx_derive": {"category": "math", "short_name": "cplx_derive"},
    "polar_to_cplx": {"category": "math", "short_name": "polar_to_cplx"},
    "scale_by_field": {"category": "math", "short_name": "scale_by_field"},
    "generalized_inner_product_fc": {
        "category": "math",
        "short_name": "generalized_inner_product_fc",
    },
    "phase": {"category": "math", "short_name": "phase"},
    "M": {"category": "result", "short_name": "nodal_moment"},
    "scale_by_field_fc": {"category": "math", "short_name": "scale_by_field_fc"},
    "cyclic_analytic_usum_max": {
        "category": "result",
        "short_name": "cyclic_analytic_usum_max",
    },
    "phase_fc": {"category": "math", "short_name": "phase_fc"},
    "modulus": {"category": "math", "short_name": "modulus"},
    "ElementalMass": {"category": "result", "short_name": "elemental_mass"},
    "accumulate_fc": {"category": "math", "short_name": "accumulate_fc"},
    "TF": {"category": "result", "short_name": "heat_flux"},
    "ENG_CO": {"category": "result", "short_name": "co_energy"},
    "generalized_inner_product": {
        "category": "math",
        "short_name": "generalized_inner_product",
    },
    "mapdl::rst::NTH_EQV": {
        "category": "result",
        "short_name": "nodal_averaged_equivalent_thermal_strains",
    },
    "native::overall_dot": {"category": "math", "short_name": "native::overall_dot"},
    "min_max_by_entity": {"category": "min_max", "short_name": "min_max_by_entity"},
    "mapdl::nmisc": {"category": "result", "short_name": "mapdl.nmisc"},
    "min_max_over_time_by_entity": {
        "category": "min_max",
        "short_name": "min_max_over_time_by_entity",
    },
    "max_over_time_by_entity": {
        "category": "min_max",
        "short_name": "max_over_time_by_entity",
    },
    "scoping::connectivity_ids": {
        "category": "scoping",
        "short_name": "connectivity_ids",
    },
    "min_over_time_by_entity": {
        "category": "min_max",
        "short_name": "min_over_time_by_entity",
    },
    "element::nodal_contribution": {
        "category": "geo",
        "short_name": "element_nodal_contribution",
    },
    "time_of_min_by_entity": {
        "category": "min_max",
        "short_name": "time_of_min_by_entity",
    },
    "max_over_phase": {"category": "min_max", "short_name": "max_over_phase"},
    "dot_tensor": {"category": "math", "short_name": "dot_tensor"},
    "invert": {"category": "math", "short_name": "invert"},
    "invert_fc": {"category": "math", "short_name": "invert_fc"},
    "EPPL3": {"category": "result", "short_name": "plastic_strain_principal_3"},
    "compare::mesh": {"category": "logic", "short_name": "identical_meshes"},
    "meshed_external_layer_sector": {
        "category": "mesh",
        "short_name": "external_layer",
    },
    "component_selector_fc": {
        "category": "logic",
        "short_name": "component_selector_fc",
    },
    "component_selector": {"category": "logic", "short_name": "component_selector"},
    "scoping_provider_by_prop": {"category": "scoping", "short_name": "on_property"},
    "ExtractFromFC": {"category": "utility", "short_name": "extract_field"},
    "mesh::node_coordinates": {"category": "mesh", "short_name": "node_coordinates"},
    "stl_export": {"category": "mesh", "short_name": "stl_export"},
    "BindSupport": {"category": "utility", "short_name": "bind_support"},
    "fieldify": {"category": "utility", "short_name": "scalars_to_field"},
    "change_location": {"category": "utility", "short_name": "change_location"},
    "strain_from_voigt": {"category": "utility", "short_name": "strain_from_voigt"},
    "field::set_property": {"category": "utility", "short_name": "set_property"},
    "forward_field": {"category": "utility", "short_name": "forward_field"},
    "mesh::points_from_coordinates": {
        "category": "mesh",
        "short_name": "points_from_coordinates",
    },
    "forward_fc": {"category": "utility", "short_name": "forward_fields_container"},
    "forward_meshes_container": {
        "category": "utility",
        "short_name": "forward_meshes_container",
    },
    "EPPL2": {"category": "result", "short_name": "plastic_strain_principal_2"},
    "element::integrate": {"category": "geo", "short_name": "integrate_over_elements"},
    "topology::center_of_gravity": {
        "category": "geo",
        "short_name": "center_of_gravity",
    },
    "forward": {"category": "utility", "short_name": "forward"},
    "text_parser": {"category": "utility", "short_name": "txt_file_to_dpf"},
    "BindSupportFC": {"category": "utility", "short_name": "bind_support_fc"},
    "GetSupportFromField": {"category": "mesh", "short_name": "from_field"},
    "PRES_Reader": {"category": "result", "short_name": "mapdl.pres_to_field"},
    "extend_to_mid_nodes_fc": {
        "category": "averaging",
        "short_name": "extend_to_mid_nodes_fc",
    },
    "ElementalNodal_To_NodalElemental_fc": {
        "category": "averaging",
        "short_name": "elemental_nodal_to_nodal_elemental_fc",
    },
    "python_generator": {"category": "utility", "short_name": ""},
    "mapdl::rst::A_cyclic": {
        "category": "result",
        "short_name": "cyclic_expanded_acceleration",
    },
    "EPELZ": {"category": "result", "short_name": "elastic_strain_Z"},
    "ResultInfoProvider": {
        "category": "metadata",
        "short_name": "result_info_provider",
    },
    "S": {"category": "result", "short_name": "stress"},
    "SX": {"category": "result", "short_name": "stress_X"},
    "SY": {"category": "result", "short_name": "stress_Y"},
    "SZ": {"category": "result", "short_name": "stress_Z"},
    "SXY": {"category": "result", "short_name": "stress_XY"},
    "SYZ": {"category": "result", "short_name": "stress_YZ"},
    "SXZ": {"category": "result", "short_name": "stress_XZ"},
    "ModalBasis": {"category": "result", "short_name": "modal_basis"},
    "S1": {"category": "result", "short_name": "stress_principal_1"},
    "expansion::modal_superposition": {
        "category": "math",
        "short_name": "expansion::modal_superposition",
    },
    "S2": {"category": "result", "short_name": "stress_principal_2"},
    "S3": {"category": "result", "short_name": "stress_principal_3"},
    "mapdl::rst::RotateNodalFCByEulerNodes": {
        "category": "result",
        "short_name": "nodal_rotation_by_euler_nodes",
    },
    "EPEL": {"category": "result", "short_name": "elastic_strain"},
    "EPELX": {"category": "result", "short_name": "elastic_strain_X"},
    "EPELXY": {"category": "result", "short_name": "elastic_strain_XY"},
    "EPELYZ": {"category": "result", "short_name": "elastic_strain_YZ"},
    "EPELXZ": {"category": "result", "short_name": "elastic_strain_XZ"},
    "eig_values_fc": {"category": "invariant", "short_name": "eigen_values_fc"},
    "EPEL1": {"category": "result", "short_name": "elastic_strain_principal_1"},
    "normals_provider": {"category": "geo", "short_name": "normals"},
    "EPEL2": {"category": "result", "short_name": "elastic_strain_principal_2"},
    "EPEL3": {"category": "result", "short_name": "elastic_strain_principal_3"},
    "to_elemental_fc": {"category": "averaging", "short_name": "to_elemental_fc"},
    "EPPL": {"category": "result", "short_name": "plastic_strain"},
    "transpose_scoping": {"category": "scoping", "short_name": "transpose"},
    "EPPLX": {"category": "result", "short_name": "plastic_strain_X"},
    "EPPLY": {"category": "result", "short_name": "plastic_strain_Y"},
    "core::field::band_pass_fc": {
        "category": "filter",
        "short_name": "field_band_pass_fc",
    },
    "polar_coordinates": {"category": "geo", "short_name": "to_polar_coordinates"},
    "EPPLZ": {"category": "result", "short_name": "plastic_strain_Z"},
    "vtk_export": {"category": "serialization", "short_name": "vtk_export"},
    "EPPLXY": {"category": "result", "short_name": "plastic_strain_XY"},
    "ENL_HPRES": {"category": "result", "short_name": "hydrostatic_pressure"},
    "EPPLYZ": {"category": "result", "short_name": "plastic_strain_YZ"},
    "core::scoping::low_pass": {"category": "filter", "short_name": "scoping_low_pass"},
    "EPPLXZ": {"category": "result", "short_name": "plastic_strain_XZ"},
    "A": {"category": "result", "short_name": "acceleration"},
    "AX": {"category": "result", "short_name": "acceleration_X"},
    "PoyntingVector": {"category": "result", "short_name": "poynting_vector"},
    "AY": {"category": "result", "short_name": "acceleration_Y"},
    "AZ": {"category": "result", "short_name": "acceleration_Z"},
    "centroids": {"category": "result", "short_name": "element_centroids"},
    "Rescope_fc": {"category": "scoping", "short_name": "rescope_fc"},
    "V": {"category": "result", "short_name": "velocity"},
    "RF": {"category": "result", "short_name": "reaction_force"},
    "serializer": {"category": "serialization", "short_name": "serializer"},
    "VX": {"category": "result", "short_name": "velocity_X"},
    "VY": {"category": "result", "short_name": "velocity_Y"},
    "VZ": {"category": "result", "short_name": "velocity_Z"},
    "U": {"category": "result", "short_name": "displacement"},
    "UX": {"category": "result", "short_name": "displacement_X"},
    "UY": {"category": "result", "short_name": "displacement_Y"},
    "UZ": {"category": "result", "short_name": "displacement_Z"},
    "TFX": {"category": "result", "short_name": "heat_flux_X"},
    "TFY": {"category": "result", "short_name": "heat_flux_Y"},
    "EF": {"category": "result", "short_name": "electric_field"},
    "TFZ": {"category": "result", "short_name": "heat_flux_Z"},
    "ENF": {"category": "result", "short_name": "element_nodal_forces"},
    "BFE": {"category": "result", "short_name": "structural_temperature"},
    "ETH": {"category": "result", "short_name": "thermal_strain"},
    "ENG_INC": {"category": "result", "short_name": "incremental_energy"},
    "mechanical_csv_to_field": {
        "category": "serialization",
        "short_name": "mechanical_csv_to_field",
    },
    "ENG_SE": {"category": "result", "short_name": "stiffness_matrix_energy"},
    "ENL_SEPL": {"category": "result", "short_name": "eqv_stress_parameter"},
    "meshed_skin_sector_triangle": {"category": "mesh", "short_name": "tri_mesh_skin"},
    "ENL_SRAT": {"category": "result", "short_name": "stress_ratio"},
    "ENL_EPEQ": {"category": "result", "short_name": "accu_eqv_plastic_strain"},
    "ENL_PSV": {"category": "result", "short_name": "plastic_state_variable"},
    "average_over_label_fc": {
        "category": "math",
        "short_name": "average_over_label_fc",
    },
    "ENL_CREQ": {"category": "result", "short_name": "accu_eqv_creep_strain"},
    "scoping::on_coordinates": {
        "category": "mapping",
        "short_name": "scoping_on_coordinates",
    },
    "ENL_PLWK": {"category": "result", "short_name": "plastic_strain_energy_density"},
    "mapdl::rst::EPEL_cyclic": {
        "category": "result",
        "short_name": "cyclic_expanded_el_strain",
    },
    "ENL_CRWK": {"category": "result", "short_name": "creep_strain_energy_density"},
    "MaterialPropertyOfElement": {
        "category": "result",
        "short_name": "material_property_of_element",
    },
    "ENL_ELENG": {"category": "result", "short_name": "elastic_strain_energy_density"},
    "ECT_STAT": {"category": "result", "short_name": "contact_status"},
    "field_to_csv": {"category": "serialization", "short_name": "field_to_csv"},
    "ECT_PENE": {"category": "result", "short_name": "contact_penetration"},
    "ECT_PRES": {"category": "result", "short_name": "contact_pressure"},
    "topology::moment_of_inertia": {
        "category": "geo",
        "short_name": "moment_of_inertia",
    },
    "ECT_SFRIC": {"category": "result", "short_name": "contact_friction_stress"},
    "ECT_STOT": {"category": "result", "short_name": "contact_total_stress"},
    "mapdl::rst::ENF_cyclic": {
        "category": "result",
        "short_name": "cyclic_expanded_enf",
    },
    "ECT_SLIDE": {"category": "result", "short_name": "contact_sliding_distance"},
    "vtk::vtk::FieldProvider": {
        "category": "serialization",
        "short_name": "vtk_to_fields",
    },
    "ECT_GAP": {"category": "result", "short_name": "contact_gap_distance"},
    "ECT_FLUX": {"category": "result", "short_name": "contact_surface_heat_flux"},
    "ECT_CNOS": {"category": "result", "short_name": "num_surface_status_changes"},
    "ECT_FRES": {
        "category": "result",
        "short_name": "contact_fluid_penetration_pressure",
    },
    "ENG_VOL": {"category": "result", "short_name": "elemental_volume"},
    "ENG_AHO": {"category": "result", "short_name": "artificial_hourglass_energy"},
    "ENG_KE": {"category": "result", "short_name": "kinetic_energy"},
    "ENG_TH": {"category": "result", "short_name": "thermal_dissipation_energy"},
    "F": {"category": "result", "short_name": "nodal_force"},
    "TEMP": {"category": "result", "short_name": "temperature"},
    "mapdl::rst::NPPL_EQV": {
        "category": "result",
        "short_name": "nodal_averaged_equivalent_plastic_strain",
    },
    "UTOT": {"category": "result", "short_name": "raw_displacement"},
    "RFTOT": {"category": "result", "short_name": "raw_reaction_force"},
    "VOLT": {"category": "result", "short_name": "electric_potential"},
    "thickness": {"category": "result", "short_name": "thickness"},
    "serialize_to_hdf5": {
        "category": "serialization",
        "short_name": "serialize_to_hdf5",
    },
    "EUL": {"category": "result", "short_name": "element_orientations"},
    "custom": {"category": "result", "short_name": "custom"},
    "S_eqv": {"category": "result", "short_name": "stress_von_mises"},
    "TimeFreqSupportProvider": {
        "category": "metadata",
        "short_name": "time_freq_provider",
    },
    "MaterialsProvider": {"category": "metadata", "short_name": "material_provider"},
    "stream_provider": {"category": "metadata", "short_name": "streams_provider"},
    "MeshProvider": {"category": "mesh", "short_name": "mesh_provider"},
    "MeshSelectionManagerProvider": {
        "category": "metadata",
        "short_name": "mesh_selection_manager_provider",
    },
    "mapdl::rst::NTH": {
        "category": "result",
        "short_name": "nodal_averaged_thermal_strains",
    },
    "boundary_conditions": {
        "category": "metadata",
        "short_name": "boundary_condition_provider",
    },
    "is_cyclic": {"category": "metadata", "short_name": "is_cyclic"},
    "mat_support_provider": {
        "category": "metadata",
        "short_name": "material_support_provider",
    },
    "deserializer": {"category": "serialization", "short_name": "deserializer"},
    "mapdl::rst::V_cyclic": {
        "category": "result",
        "short_name": "cyclic_expanded_velocity",
    },
    "compare::property_field": {
        "category": "logic",
        "short_name": "identical_property_fields",
    },
    "min_max": {"category": "min_max", "short_name": "min_max"},
    "min_max_fc": {"category": "min_max", "short_name": "min_max_fc"},
    "min_max_over_label_fc": {
        "category": "min_max",
        "short_name": "min_max_over_label_fc",
    },
    "min_by_component": {"category": "min_max", "short_name": "min_by_component"},
    "max_by_component": {"category": "min_max", "short_name": "max_by_component"},
    "merge::fields_container_label": {
        "category": "logic",
        "short_name": "merge_fields_by_label",
    },
    "min_max_fc_inc": {"category": "min_max", "short_name": "min_max_fc_inc"},
    "scoping::by_property": {
        "category": "scoping",
        "short_name": "splitted_on_property_type",
    },
    "min_max_inc": {"category": "min_max", "short_name": "min_max_inc"},
    "accumulate_over_label_fc": {
        "category": "math",
        "short_name": "accumulate_over_label_fc",
    },
    "ERP": {"category": "result", "short_name": "equivalent_radiated_power"},
    "accumulate_level_over_label_fc": {
        "category": "math",
        "short_name": "accumulate_level_over_label_fc",
    },
    "Rescope": {"category": "scoping", "short_name": "rescope"},
    "scoping_provider_by_ns": {
        "category": "scoping",
        "short_name": "on_named_selection",
    },
    "mapdl::rst::support_provider_cyclic": {
        "category": "metadata",
        "short_name": "cyclic_support_provider",
    },
    "GetNodeScopingFromMesh": {"category": "scoping", "short_name": "nodal_from_mesh"},
    "rescope_fc": {"category": "scoping", "short_name": "change_fc"},
    "ElementalNodal_To_NodalElemental": {
        "category": "averaging",
        "short_name": "elemental_nodal_to_nodal_elemental",
    },
    "change_shellLayers": {"category": "utility", "short_name": "change_shell_layers"},
    "merge::solid_shell_fields": {
        "category": "logic",
        "short_name": "merge::solid_shell_fields",
    },
    "AreFieldsIdentical": {"category": "logic", "short_name": "identical_fields"},
    "Are_fields_included": {"category": "logic", "short_name": "included_fields"},
    "AreFieldsIdentical_fc": {"category": "logic", "short_name": "identical_fc"},
    "core::field::high_pass": {"category": "filter", "short_name": "field_high_pass"},
    "core::scoping::high_pass": {
        "category": "filter",
        "short_name": "scoping_high_pass",
    },
    "core::field::high_pass_fc": {
        "category": "filter",
        "short_name": "field_high_pass_fc",
    },
    "core::field::low_pass": {"category": "filter", "short_name": "field_low_pass"},
    "core::field::low_pass_fc": {
        "category": "filter",
        "short_name": "field_low_pass_fc",
    },
    "core::field::band_pass": {"category": "filter", "short_name": "field_band_pass"},
    "transform_cylindricalCS": {
        "category": "geo",
        "short_name": "rotate_in_cylindrical_cs",
    },
    "core::scoping::band_pass": {
        "category": "filter",
        "short_name": "scoping_band_pass",
    },
    "mapdl::run": {"category": "result", "short_name": "mapdl.run"},
    "csv_to_field": {"category": "serialization", "short_name": "csv_to_field"},
    "rotate": {"category": "geo", "short_name": "rotate"},
    "enrich_materials": {"category": "logic", "short_name": "enrich_materials"},
    "elemental_nodal_To_nodal": {
        "category": "averaging",
        "short_name": "elemental_nodal_to_nodal",
    },
    "elemental_nodal_To_nodal_fc": {
        "category": "averaging",
        "short_name": "elemental_nodal_to_nodal_fc",
    },
    "elemental_to_nodal": {"category": "averaging", "short_name": "elemental_to_nodal"},
    "elemental_to_nodal_fc": {
        "category": "averaging",
        "short_name": "elemental_to_nodal_fc",
    },
    "nodal_difference": {"category": "averaging", "short_name": "nodal_difference"},
    "eig_vectors": {"category": "invariant", "short_name": "eigen_vectors"},
    "nodal_difference_fc": {
        "category": "averaging",
        "short_name": "nodal_difference_fc",
    },
    "elemental_difference": {
        "category": "averaging",
        "short_name": "elemental_difference",
    },
    "elemental_difference_fc": {
        "category": "averaging",
        "short_name": "elemental_difference_fc",
    },
    "to_nodal": {"category": "averaging", "short_name": "to_nodal"},
    "transform_cylindrical_cs_fc": {
        "category": "geo",
        "short_name": "rotate_in_cylindrical_cs_fc",
    },
    "eig_values": {"category": "invariant", "short_name": "eigen_values"},
    "to_nodal_fc": {"category": "averaging", "short_name": "to_nodal_fc"},
    "extend_to_mid_nodes": {
        "category": "averaging",
        "short_name": "extend_to_mid_nodes",
    },
    "entity_average": {"category": "averaging", "short_name": "elemental_mean"},
    "entity_average_fc": {"category": "averaging", "short_name": "elemental_mean_fc"},
    "gauss_to_node_fc": {"category": "averaging", "short_name": "gauss_to_node_fc"},
    "nodal_to_elemental": {"category": "averaging", "short_name": "nodal_to_elemental"},
    "nodal_to_elemental_fc": {
        "category": "averaging",
        "short_name": "nodal_to_elemental_fc",
    },
    "eqv": {"category": "invariant", "short_name": "von_mises_eqv"},
    "invariants_deriv": {"category": "invariant", "short_name": "invariants"},
    "invariants": {"category": "invariant", "short_name": "principal_invariants"},
    "eqv_fc": {"category": "invariant", "short_name": "von_mises_eqv_fc"},
    "invariants_deriv_fc": {"category": "invariant", "short_name": "invariants_fc"},
    "mapdl::rst::ENG_SE_cyclic": {
        "category": "result",
        "short_name": "cyclic_strain_energy",
    },
    "invariants_fc": {"category": "invariant", "short_name": "principal_invariants_fc"},
    "rotate_fc": {"category": "geo", "short_name": "rotate_fc"},
    "normals_provider_nl": {"category": "geo", "short_name": "normals_provider_nl"},
    "volumes_provider": {"category": "geo", "short_name": "elements_volumes_over_time"},
    "surfaces_provider": {
        "category": "geo",
        "short_name": "elements_facets_surfaces_over_time",
    },
    "MeshScopingProvider": {"category": "scoping", "short_name": "from_mesh"},
    "mesh::by_scoping": {"category": "mesh", "short_name": "from_scoping"},
    "split_fields": {"category": "mesh", "short_name": "split_fields"},
    "split_mesh": {"category": "mesh", "short_name": "split_mesh"},
    "meshscoping_provider_by_prop": {
        "category": "scoping",
        "short_name": "on_mesh_property",
    },
    "gauss_to_node": {"category": "geo", "short_name": "gauss_to_node"},
    "torque": {"category": "result", "short_name": "torque"},
    "cyclic_expansion_mesh": {
        "category": "metadata",
        "short_name": "cyclic_mesh_expansion",
    },
    "cyclic_analytic_stress_eqv_max": {
        "category": "result",
        "short_name": "cyclic_analytic_seqv_max",
    },
    "ExtractRigidBodyMotion_fc": {
        "category": "result",
        "short_name": "remove_rigid_body_motion_fc",
    },
    "recombine_harmonic_indeces_cyclic": {
        "category": "result",
        "short_name": "recombine_harmonic_indeces_cyclic",
    },
    "mapping": {"category": "mapping", "short_name": "on_coordinates"},
    "solid_to_skin": {"category": "mapping", "short_name": "solid_to_skin"},
    "element::volume": {"category": "geo", "short_name": "elements_volume"},
    "mapdl::rst::NTH_SWL": {
        "category": "result",
        "short_name": "nodal_averaged_thermal_swelling_strains",
    },
    "PoyntingVectorSurface": {
        "category": "result",
        "short_name": "poynting_vector_surface",
    },
    "RigidBodyAddition": {"category": "result", "short_name": "add_rigid_body_motion"},
    "mapdl::rst::NS": {"category": "result", "short_name": "nodal_averaged_stresses"},
    "mapdl::rst::NPPL": {
        "category": "result",
        "short_name": "nodal_averaged_plastic_strains",
    },
    "mapdl::rst::NCR": {
        "category": "result",
        "short_name": "nodal_averaged_creep_strains",
    },
    "mapdl::rst::NPEL_EQV": {
        "category": "result",
        "short_name": "nodal_averaged_equivalent_elastic_strain",
    },
    "mapdl::rst::NCR_EQV": {
        "category": "result",
        "short_name": "nodal_averaged_equivalent_creep_strain",
    },
    "mapdl::rst::coords_and_euler_nodes": {
        "category": "result",
        "short_name": "euler_nodes",
    },
    "ENF_rotation_by_euler_nodes": {
        "category": "result",
        "short_name": "enf_rotation_by_euler_nodes",
    },
    "cms_matrices_provider": {
        "category": "result",
        "short_name": "cms_matrices_provider",
    },
    "meshed_skin_sector": {"category": "mesh", "short_name": "skin"},
    "mapdl::smisc": {"category": "result", "short_name": "mapdl.smisc"},
    "mapdl::rst::S_rotation_by_euler_nodes": {
        "category": "result",
        "short_name": "stress_rotation_by_euler_nodes",
    },
    "mapdl::rst::EPEL_rotation_by_euler_nodes": {
        "category": "result",
        "short_name": "elastic_strain_rotation_by_euler_nodes",
    },
    "mapdl::rst::EPPL_rotation_by_euler_nodes": {
        "category": "result",
        "short_name": "plastic_strain_rotation_by_euler_nodes",
    },
    "PRNS_Reader": {"category": "result", "short_name": "mapdl.prns_to_field"},
    "mesh_cut": {"category": "mesh", "short_name": "mesh_cut"},
    "ExtractRigidBodyMotion": {
        "category": "result",
        "short_name": "remove_rigid_body_motion",
    },
    "RigidBodyAddition_fc": {
        "category": "result",
        "short_name": "add_rigid_body_motion_fc",
    },
    "mapdl::rst::U_cyclic": {
        "category": "result",
        "short_name": "cyclic_expanded_displacement",
    },
    "mapdl::rst::S_cyclic": {
        "category": "result",
        "short_name": "cyclic_expanded_stress",
    },
    "mapdl::rst::ENG_VOL_cyclic": {"category": "result", "short_name": "cyclic_volume"},
    "eig_vectors_fc": {"category": "invariant", "short_name": "eigen_vectors_fc"},
    "grpc_server_start": {"category": "other", "short_name": "grpc_server_start"},
    "vtk::migrate_file": {
        "category": "serialization",
        "short_name": "migrate_file_to_vtk",
    },
    "hdf5::h5dpf::migrate_file": {
        "category": "result",
        "short_name": "migrate_to_h5dpf",
    },
}
