operators = {'A': {'category': 'result', 'short_name': 'acceleration'},
 'AX': {'category': 'result', 'short_name': 'acceleration_X'},
 'AY': {'category': 'result', 'short_name': 'acceleration_Y'},
 'AZ': {'category': 'result', 'short_name': 'acceleration_Z'},
 'AreFieldsIdentical': {'category': 'logic',
                        'short_name': 'identical_fields'},
 'AreFieldsIdentical_fc': {'category': 'logic',
                           'short_name': 'identical_fc'},
 'Are_fields_included': {'category': 'logic',
                         'short_name': 'included_fields'},
 'BFE': {'category': 'result',
         'short_name': 'structural_temperature'},
 'BindSupport': {'category': 'utility', 'short_name': 'bind_support'},
 'BindSupportFC': {'category': 'utility',
                   'short_name': 'bind_support_fc'},
 'CplxOp': {'category': 'math', 'short_name': 'linear_combination'},
 'ECT_CNOS': {'category': 'result',
              'short_name': 'num_surface_status_changes'},
 'ECT_FLUX': {'category': 'result',
              'short_name': 'contact_surface_heat_flux'},
 'ECT_FRES': {'category': 'result',
              'short_name': 'contact_fluid_penetration_pressure'},
 'ECT_GAP': {'category': 'result',
             'short_name': 'contact_gap_distance'},
 'ECT_PENE': {'category': 'result',
              'short_name': 'contact_penetration'},
 'ECT_PRES': {'category': 'result', 'short_name': 'contact_pressure'},
 'ECT_SFRIC': {'category': 'result',
               'short_name': 'contact_friction_stress'},
 'ECT_SLIDE': {'category': 'result',
               'short_name': 'contact_sliding_distance'},
 'ECT_STAT': {'category': 'result', 'short_name': 'contact_status'},
 'ECT_STOT': {'category': 'result',
              'short_name': 'contact_total_stress'},
 'EF': {'category': 'result', 'short_name': 'electric_field'},
 'ENF': {'category': 'result', 'short_name': 'element_nodal_forces'},
 'ENF_rotation_by_euler_nodes': {'category': 'result',
                                 'short_name': 'enf_rotation_by_euler_nodes'},
 'ENG_AHO': {'category': 'result',
             'short_name': 'artificial_hourglass_energy'},
 'ENG_CO': {'category': 'result', 'short_name': 'co_energy'},
 'ENG_INC': {'category': 'result',
             'short_name': 'incremental_energy'},
 'ENG_KE': {'category': 'result', 'short_name': 'kinetic_energy'},
 'ENG_SE': {'category': 'result',
            'short_name': 'stiffness_matrix_energy'},
 'ENG_TH': {'category': 'result',
            'short_name': 'thermal_dissipation_energy'},
 'ENG_VOL': {'category': 'result', 'short_name': 'elemental_volume'},
 'ENL_CREQ': {'category': 'result',
              'short_name': 'accu_eqv_creep_strain'},
 'ENL_CRWK': {'category': 'result',
              'short_name': 'creep_strain_energy_density'},
 'ENL_ELENG': {'category': 'result',
               'short_name': 'elastic_strain_energy_density'},
 'ENL_EPEQ': {'category': 'result',
              'short_name': 'accu_eqv_plastic_strain'},
 'ENL_HPRES': {'category': 'result',
               'short_name': 'hydrostatic_pressure'},
 'ENL_PLWK': {'category': 'result',
              'short_name': 'plastic_strain_energy_density'},
 'ENL_PSV': {'category': 'result',
             'short_name': 'plastic_state_variable'},
 'ENL_SEPL': {'category': 'result',
              'short_name': 'eqv_stress_parameter'},
 'ENL_SRAT': {'category': 'result', 'short_name': 'stress_ratio'},
 'EPEL': {'category': 'result', 'short_name': 'elastic_strain'},
 'EPEL1': {'category': 'result',
           'short_name': 'elastic_strain_principal_1'},
 'EPEL2': {'category': 'result',
           'short_name': 'elastic_strain_principal_2'},
 'EPEL3': {'category': 'result',
           'short_name': 'elastic_strain_principal_3'},
 'EPELX': {'category': 'result', 'short_name': 'elastic_strain_X'},
 'EPELXY': {'category': 'result', 'short_name': 'elastic_strain_XY'},
 'EPELXZ': {'category': 'result', 'short_name': 'elastic_strain_XZ'},
 'EPELY': {'category': 'result', 'short_name': 'elastic_strain_Y'},
 'EPELYZ': {'category': 'result', 'short_name': 'elastic_strain_YZ'},
 'EPELZ': {'category': 'result', 'short_name': 'elastic_strain_Z'},
 'EPPL': {'category': 'result', 'short_name': 'plastic_strain'},
 'EPPL1': {'category': 'result',
           'short_name': 'plastic_strain_principal_1'},
 'EPPL2': {'category': 'result',
           'short_name': 'plastic_strain_principal_2'},
 'EPPL3': {'category': 'result',
           'short_name': 'plastic_strain_principal_3'},
 'EPPLX': {'category': 'result', 'short_name': 'plastic_strain_X'},
 'EPPLXY': {'category': 'result', 'short_name': 'plastic_strain_XY'},
 'EPPLXZ': {'category': 'result', 'short_name': 'plastic_strain_XZ'},
 'EPPLY': {'category': 'result', 'short_name': 'plastic_strain_Y'},
 'EPPLYZ': {'category': 'result', 'short_name': 'plastic_strain_YZ'},
 'EPPLZ': {'category': 'result', 'short_name': 'plastic_strain_Z'},
 'ERP': {'category': 'result',
         'short_name': 'equivalent_radiated_power'},
 'ETH': {'category': 'result', 'short_name': 'thermal_strain'},
 'ElementalMass': {'category': 'result',
                   'short_name': 'elemental_mass'},
 'ElementalNodal_To_NodalElemental': {'category': 'averaging',
                                      'short_name': 'elemental_nodal_to_nodal_elemental'},
 'ElementalNodal_To_NodalElemental_fc': {'category': 'averaging',
                                         'short_name': 'elemental_nodal_to_nodal_elemental_fc'},
 'ExtractFromFC': {'category': 'utility',
                   'short_name': 'extract_field'},
 'ExtractRigidBodyMotion': {'category': 'result',
                            'short_name': 'remove_rigid_body_motion'},
 'ExtractRigidBodyMotion_fc': {'category': 'result',
                               'short_name': 'remove_rigid_body_motion_fc'},
 'F': {'category': 'result', 'short_name': 'nodal_force'},
 'GetElementScopingFromMesh': {'category': 'scoping',
                               'short_name': 'elemental_from_mesh'},
 'GetNodeScopingFromMesh': {'category': 'scoping',
                            'short_name': 'nodal_from_mesh'},
 'GetSupportFromField': {'category': 'mesh',
                         'short_name': 'from_field'},
 'InjectToFieldContainer': {'category': 'utility',
                            'short_name': 'field_to_fc'},
 'M': {'category': 'result', 'short_name': 'nodal_moment'},
 'MaterialPropertyOfElement': {'category': 'result',
                               'short_name': 'material_property_of_element'},
 'MaterialsProvider': {'category': 'metadata',
                       'short_name': 'material_provider'},
 'MeshProvider': {'category': 'mesh', 'short_name': 'mesh_provider'},
 'MeshScopingProvider': {'category': 'scoping',
                         'short_name': 'from_mesh'},
 'MeshSelectionManagerProvider': {'category': 'metadata',
                                  'short_name': 'mesh_selection_manager_provider'},
 'ModalBasis': {'category': 'result', 'short_name': 'modal_basis'},
 'PRES_Reader': {'category': 'result',
                 'short_name': 'mapdl.pres_to_field'},
 'PRNS_Reader': {'category': 'result',
                 'short_name': 'mapdl.prns_to_field'},
 'Pow': {'category': 'math', 'short_name': 'pow'},
 'Pow_fc': {'category': 'math', 'short_name': 'pow_fc'},
 'PoyntingVector': {'category': 'result',
                    'short_name': 'poynting_vector'},
 'PoyntingVectorSurface': {'category': 'result',
                           'short_name': 'poynting_vector_surface'},
 'RF': {'category': 'result', 'short_name': 'reaction_force'},
 'RFTOT': {'category': 'result', 'short_name': 'raw_reaction_force'},
 'Rescope': {'category': 'scoping', 'short_name': 'rescope'},
 'Rescope_fc': {'category': 'scoping', 'short_name': 'rescope_fc'},
 'ResultInfoProvider': {'category': 'metadata',
                        'short_name': 'result_info_provider'},
 'RigidBodyAddition': {'category': 'result',
                       'short_name': 'add_rigid_body_motion'},
 'RigidBodyAddition_fc': {'category': 'result',
                          'short_name': 'add_rigid_body_motion_fc'},
 'RigidTransformationProvider': {'category': 'result',
                                 'short_name': 'rigid_transformation'},
 'S': {'category': 'result', 'short_name': 'stress'},
 'S1': {'category': 'result', 'short_name': 'stress_principal_1'},
 'S2': {'category': 'result', 'short_name': 'stress_principal_2'},
 'S3': {'category': 'result', 'short_name': 'stress_principal_3'},
 'SX': {'category': 'result', 'short_name': 'stress_X'},
 'SXY': {'category': 'result', 'short_name': 'stress_XY'},
 'SXZ': {'category': 'result', 'short_name': 'stress_XZ'},
 'SY': {'category': 'result', 'short_name': 'stress_Y'},
 'SYZ': {'category': 'result', 'short_name': 'stress_YZ'},
 'SZ': {'category': 'result', 'short_name': 'stress_Z'},
 'S_eqv': {'category': 'result', 'short_name': 'stress_von_mises'},
 'TEMP': {'category': 'result', 'short_name': 'temperature'},
 'TF': {'category': 'result', 'short_name': 'heat_flux'},
 'TFX': {'category': 'result', 'short_name': 'heat_flux_X'},
 'TFY': {'category': 'result', 'short_name': 'heat_flux_Y'},
 'TFZ': {'category': 'result', 'short_name': 'heat_flux_Z'},
 'TimeFreqSupportProvider': {'category': 'metadata',
                             'short_name': 'time_freq_provider'},
 'U': {'category': 'result', 'short_name': 'displacement'},
 'UTOT': {'category': 'result', 'short_name': 'raw_displacement'},
 'UX': {'category': 'result', 'short_name': 'displacement_X'},
 'UY': {'category': 'result', 'short_name': 'displacement_Y'},
 'UZ': {'category': 'result', 'short_name': 'displacement_Z'},
 'V': {'category': 'result', 'short_name': 'velocity'},
 'VOLT': {'category': 'result', 'short_name': 'electric_potential'},
 'VX': {'category': 'result', 'short_name': 'velocity_X'},
 'VY': {'category': 'result', 'short_name': 'velocity_Y'},
 'VZ': {'category': 'result', 'short_name': 'velocity_Z'},
 'accumulate': {'category': 'math', 'short_name': 'accumulate'},
 'accumulate_fc': {'category': 'math', 'short_name': 'accumulate_fc'},
 'accumulate_level_over_label_fc': {'category': 'math',
                                    'short_name': 'accumulate_level_over_label_fc'},
 'accumulate_min_over_label_fc': {'category': 'math',
                                  'short_name': 'accumulate_min_over_label_fc'},
 'accumulate_over_label_fc': {'category': 'math',
                              'short_name': 'accumulate_over_label_fc'},
 'add': {'category': 'math', 'short_name': 'add'},
 'add_constant': {'category': 'math', 'short_name': 'add_constant'},
 'add_constant_fc': {'category': 'math',
                     'short_name': 'add_constant_fc'},
 'add_fc': {'category': 'math', 'short_name': 'add_fc'},
 'amplitude': {'category': 'math', 'short_name': 'amplitude'},
 'amplitude_fc': {'category': 'math', 'short_name': 'amplitude_fc'},
 'average_over_label_fc': {'category': 'math',
                           'short_name': 'average_over_label_fc'},
 'boundary_conditions': {'category': 'metadata',
                         'short_name': 'boundary_condition_provider'},
 'centroid': {'category': 'math', 'short_name': 'centroid'},
 'centroid_fc': {'category': 'math', 'short_name': 'centroid_fc'},
 'centroids': {'category': 'result',
               'short_name': 'element_centroids'},
 'change_location': {'category': 'utility',
                     'short_name': 'change_location'},
 'change_shellLayers': {'category': 'utility',
                        'short_name': 'change_shell_layers'},
 'cms_matrices_provider': {'category': 'result',
                           'short_name': 'cms_matrices_provider'},
 'compare::mesh': {'category': 'logic',
                   'short_name': 'identical_meshes'},
 'compare::property_field': {'category': 'logic',
                             'short_name': 'identical_property_fields'},
 'component_selector': {'category': 'logic',
                        'short_name': 'component_selector'},
 'component_selector_fc': {'category': 'logic',
                           'short_name': 'component_selector_fc'},
 'component_wise_divide': {'category': 'math',
                           'short_name': 'component_wise_divide'},
 'component_wise_divide_fc': {'category': 'math',
                              'short_name': 'component_wise_divide_fc'},
 'conjugate': {'category': 'math', 'short_name': 'conjugate'},
 'core::field::band_pass': {'category': 'filter',
                            'short_name': 'field_band_pass'},
 'core::field::band_pass_fc': {'category': 'filter',
                               'short_name': 'field_band_pass_fc'},
 'core::field::high_pass': {'category': 'filter',
                            'short_name': 'field_high_pass'},
 'core::field::high_pass_fc': {'category': 'filter',
                               'short_name': 'field_high_pass_fc'},
 'core::field::low_pass': {'category': 'filter',
                           'short_name': 'field_low_pass'},
 'core::field::low_pass_fc': {'category': 'filter',
                              'short_name': 'field_low_pass_fc'},
 'core::scoping::band_pass': {'category': 'filter',
                              'short_name': 'scoping_band_pass'},
 'core::scoping::high_pass': {'category': 'filter',
                              'short_name': 'scoping_high_pass'},
 'core::scoping::low_pass': {'category': 'filter',
                             'short_name': 'scoping_low_pass'},
 'cos': {'category': 'math', 'short_name': 'cos'},
 'cos_fc': {'category': 'math', 'short_name': 'cos_fc'},
 'cplx_add': {'category': 'math', 'short_name': 'cplx_add'},
 'cplx_derive': {'category': 'math', 'short_name': 'cplx_derive'},
 'cplx_divide': {'category': 'math', 'short_name': 'cplx_divide'},
 'cplx_dot': {'category': 'math', 'short_name': 'cplx_dot'},
 'cplx_multiply': {'category': 'math', 'short_name': 'cplx_multiply'},
 'csv_to_field': {'category': 'serialization',
                  'short_name': 'csv_to_field'},
 'custom': {'category': 'result', 'short_name': 'custom'},
 'cyclic_analytic_stress_eqv_max': {'category': 'result',
                                    'short_name': 'cyclic_analytic_seqv_max'},
 'cyclic_analytic_usum_max': {'category': 'result',
                              'short_name': 'cyclic_analytic_usum_max'},
 'cyclic_expansion': {'category': 'result',
                      'short_name': 'cyclic_expansion'},
 'cyclic_expansion_mesh': {'category': 'metadata',
                           'short_name': 'cyclic_mesh_expansion'},
 'deserializer': {'category': 'serialization',
                  'short_name': 'deserializer'},
 'dot': {'category': 'math', 'short_name': 'dot'},
 'dot_tensor': {'category': 'math', 'short_name': 'dot_tensor'},
 'eig_values': {'category': 'invariant',
                'short_name': 'eigen_values'},
 'eig_values_fc': {'category': 'invariant',
                   'short_name': 'eigen_values_fc'},
 'eig_vectors': {'category': 'invariant',
                 'short_name': 'eigen_vectors'},
 'eig_vectors_fc': {'category': 'invariant',
                    'short_name': 'eigen_vectors_fc'},
 'element::integrate': {'category': 'geo',
                        'short_name': 'integrate_over_elements'},
 'element::nodal_contribution': {'category': 'geo',
                                 'short_name': 'element_nodal_contribution'},
 'element::volume': {'category': 'geo',
                     'short_name': 'elements_volume'},
 'elemental_difference': {'category': 'averaging',
                          'short_name': 'elemental_difference'},
 'elemental_difference_fc': {'category': 'averaging',
                             'short_name': 'elemental_difference_fc'},
 'elemental_fraction_fc': {'category': 'averaging',
                           'short_name': 'elemental_fraction_fc'},
 'elemental_nodal_To_nodal': {'category': 'averaging',
                              'short_name': 'elemental_nodal_to_nodal'},
 'elemental_nodal_To_nodal_fc': {'category': 'averaging',
                                 'short_name': 'elemental_nodal_to_nodal_fc'},
 'elemental_to_nodal': {'category': 'averaging',
                        'short_name': 'elemental_to_nodal'},
 'elemental_to_nodal_fc': {'category': 'averaging',
                           'short_name': 'elemental_to_nodal_fc'},
 'enrich_materials': {'category': 'logic',
                      'short_name': 'enrich_materials'},
 'entity_average': {'category': 'averaging',
                    'short_name': 'elemental_mean'},
 'entity_average_fc': {'category': 'averaging',
                       'short_name': 'elemental_mean_fc'},
 'eqv': {'category': 'invariant', 'short_name': 'von_mises_eqv'},
 'eqv_fc': {'category': 'invariant',
            'short_name': 'von_mises_eqv_fc'},
 'expansion::modal_superposition': {'category': 'math',
                                    'short_name': 'expansion::modal_superposition'},
 'extend_to_mid_nodes': {'category': 'averaging',
                         'short_name': 'extend_to_mid_nodes'},
 'extend_to_mid_nodes_fc': {'category': 'averaging',
                            'short_name': 'extend_to_mid_nodes_fc'},
 'field::set_property': {'category': 'utility',
                         'short_name': 'set_property'},
 'field_to_csv': {'category': 'serialization',
                  'short_name': 'field_to_csv'},
 'fieldify': {'category': 'utility',
              'short_name': 'scalars_to_field'},
 'forward': {'category': 'utility', 'short_name': 'forward'},
 'forward_fc': {'category': 'utility',
                'short_name': 'forward_fields_container'},
 'forward_field': {'category': 'utility',
                   'short_name': 'forward_field'},
 'forward_meshes_container': {'category': 'utility',
                              'short_name': 'forward_meshes_container'},
 'generalized_inner_product': {'category': 'math',
                               'short_name': 'generalized_inner_product'},
 'generalized_inner_product_fc': {'category': 'math',
                                  'short_name': 'generalized_inner_product_fc'},
 'html_doc': {'category': 'utility', 'short_name': 'html_doc'},
 'img_part': {'category': 'math', 'short_name': 'img_part'},
 'invariants': {'category': 'invariant',
                'short_name': 'principal_invariants'},
 'invariants_deriv': {'category': 'invariant',
                      'short_name': 'invariants'},
 'invariants_deriv_fc': {'category': 'invariant',
                         'short_name': 'invariants_fc'},
 'invariants_fc': {'category': 'invariant',
                   'short_name': 'principal_invariants_fc'},
 'invert': {'category': 'math', 'short_name': 'invert'},
 'invert_fc': {'category': 'math', 'short_name': 'invert_fc'},
 'is_cyclic': {'category': 'metadata', 'short_name': 'is_cyclic'},
 'kronecker_prod': {'category': 'math',
                    'short_name': 'kronecker_prod'},
 'make_unit': {'category': 'utility', 'short_name': 'unitary_field'},
 'mapdl::nmisc': {'category': 'result', 'short_name': 'mapdl.nmisc'},
 'mapdl::rst::A_cyclic': {'category': 'result',
                          'short_name': 'cyclic_expanded_acceleration'},
 'mapdl::rst::ENF_cyclic': {'category': 'result',
                            'short_name': 'cyclic_expanded_enf'},
 'mapdl::rst::ENG_SE_cyclic': {'category': 'result',
                               'short_name': 'cyclic_strain_energy'},
 'mapdl::rst::ENG_VOL_cyclic': {'category': 'result',
                                'short_name': 'cyclic_volume'},
 'mapdl::rst::EPEL_cyclic': {'category': 'result',
                             'short_name': 'cyclic_expanded_el_strain'},
 'mapdl::rst::EPEL_rotation_by_euler_nodes': {'category': 'result',
                                              'short_name': 'elastic_strain_rotation_by_euler_nodes'},
 'mapdl::rst::EPPL_rotation_by_euler_nodes': {'category': 'result',
                                              'short_name': 'plastic_strain_rotation_by_euler_nodes'},
 'mapdl::rst::NCR': {'category': 'result',
                     'short_name': 'nodal_averaged_creep_strains'},
 'mapdl::rst::NCR_EQV': {'category': 'result',
                         'short_name': 'nodal_averaged_equivalent_creep_strain'},
 'mapdl::rst::NPEL': {'category': 'result',
                      'short_name': 'nodal_averaged_elastic_strains'},
 'mapdl::rst::NPEL_EQV': {'category': 'result',
                          'short_name': 'nodal_averaged_equivalent_elastic_strain'},
 'mapdl::rst::NPPL': {'category': 'result',
                      'short_name': 'nodal_averaged_plastic_strains'},
 'mapdl::rst::NPPL_EQV': {'category': 'result',
                          'short_name': 'nodal_averaged_equivalent_plastic_strain'},
 'mapdl::rst::NS': {'category': 'result',
                    'short_name': 'nodal_averaged_stresses'},
 'mapdl::rst::NTH': {'category': 'result',
                     'short_name': 'nodal_averaged_thermal_strains'},
 'mapdl::rst::NTH_EQV': {'category': 'result',
                         'short_name': 'nodal_averaged_equivalent_thermal_strains'},
 'mapdl::rst::NTH_SWL': {'category': 'result',
                         'short_name': 'nodal_averaged_thermal_swelling_strains'},
 'mapdl::rst::RotateNodalFCByEulerNodes': {'category': 'result',
                                           'short_name': 'nodal_rotation_by_euler_nodes'},
 'mapdl::rst::S_cyclic': {'category': 'result',
                          'short_name': 'cyclic_expanded_stress'},
 'mapdl::rst::S_rotation_by_euler_nodes': {'category': 'result',
                                           'short_name': 'stress_rotation_by_euler_nodes'},
 'mapdl::rst::U_cyclic': {'category': 'result',
                          'short_name': 'cyclic_expanded_displacement'},
 'mapdl::rst::V_cyclic': {'category': 'result',
                          'short_name': 'cyclic_expanded_velocity'},
 'mapdl::rst::coords_and_euler_nodes': {'category': 'result',
                                        'short_name': 'euler_nodes'},
 'mapdl::rst::support_provider_cyclic': {'category': 'metadata',
                                         'short_name': 'cyclic_support_provider'},
 'mapdl::run': {'category': 'result', 'short_name': 'mapdl.run'},
 'mapdl::smisc': {'category': 'result', 'short_name': 'mapdl.smisc'},
 'mapping': {'category': 'mapping', 'short_name': 'on_coordinates'},
 'mat_support_provider': {'category': 'metadata',
                          'short_name': 'material_support_provider'},
 'max_by_component': {'category': 'min_max',
                      'short_name': 'max_by_component'},
 'max_over_phase': {'category': 'min_max',
                    'short_name': 'max_over_phase'},
 'max_over_time_by_entity': {'category': 'min_max',
                             'short_name': 'max_over_time_by_entity'},
 'mechanical_csv_to_field': {'category': 'serialization',
                             'short_name': 'mechanical_csv_to_field'},
 'merge::fields_container_label': {'category': 'logic',
                                   'short_name': 'merge_fields_by_label'},
 'merge::solid_shell_fields': {'category': 'logic',
                               'short_name': 'merge::solid_shell_fields'},
 'mesh::by_scoping': {'category': 'mesh',
                      'short_name': 'from_scoping'},
 'mesh::node_coordinates': {'category': 'mesh',
                            'short_name': 'node_coordinates'},
 'mesh::points_from_coordinates': {'category': 'mesh',
                                   'short_name': 'points_from_coordinates'},
 'mesh_cut': {'category': 'mesh', 'short_name': 'mesh_cut'},
 'mesh_support_provider': {'category': 'metadata',
                           'short_name': 'mesh_support_provider'},
 'meshed_external_layer_sector': {'category': 'mesh',
                                  'short_name': 'external_layer'},
 'meshed_skin_sector': {'category': 'mesh', 'short_name': 'skin'},
 'meshed_skin_sector_triangle': {'category': 'mesh',
                                 'short_name': 'tri_mesh_skin'},
 'min_by_component': {'category': 'min_max',
                      'short_name': 'min_by_component'},
 'min_max': {'category': 'min_max', 'short_name': 'min_max'},
 'min_max_by_entity': {'category': 'min_max',
                       'short_name': 'min_max_by_entity'},
 'min_max_by_time': {'category': 'min_max',
                     'short_name': 'min_max_by_time'},
 'min_max_fc': {'category': 'min_max', 'short_name': 'min_max_fc'},
 'min_max_fc_inc': {'category': 'min_max',
                    'short_name': 'min_max_fc_inc'},
 'min_max_inc': {'category': 'min_max', 'short_name': 'min_max_inc'},
 'min_max_over_label_fc': {'category': 'min_max',
                           'short_name': 'min_max_over_label_fc'},
 'min_max_over_time_by_entity': {'category': 'min_max',
                                 'short_name': 'min_max_over_time_by_entity'},
 'min_over_time_by_entity': {'category': 'min_max',
                             'short_name': 'min_over_time_by_entity'},
 'minus': {'category': 'math', 'short_name': 'minus'},
 'minus_fc': {'category': 'math', 'short_name': 'minus_fc'},
 'modulus': {'category': 'math', 'short_name': 'modulus'},
 'native::overall_dot': {'category': 'math',
                         'short_name': 'native::overall_dot'},
 'nodal_difference': {'category': 'averaging',
                      'short_name': 'nodal_difference'},
 'nodal_difference_fc': {'category': 'averaging',
                         'short_name': 'nodal_difference_fc'},
 'nodal_fraction_fc': {'category': 'averaging',
                       'short_name': 'nodal_fraction_fc'},
 'nodal_to_elemental': {'category': 'averaging',
                        'short_name': 'nodal_to_elemental'},
 'nodal_to_elemental_fc': {'category': 'averaging',
                           'short_name': 'nodal_to_elemental_fc'},
 'norm': {'category': 'math', 'short_name': 'norm'},
 'norm_fc': {'category': 'math', 'short_name': 'norm_fc'},
 'normals_provider': {'category': 'geo', 'short_name': 'normals'},
 'normals_provider_nl': {'category': 'geo',
                         'short_name': 'normals_provider_nl'},
 'phase': {'category': 'math', 'short_name': 'phase'},
 'phase_fc': {'category': 'math', 'short_name': 'phase_fc'},
 'phase_of_max': {'category': 'min_max',
                  'short_name': 'phase_of_max'},
 'polar_coordinates': {'category': 'geo',
                       'short_name': 'to_polar_coordinates'},
 'polar_to_cplx': {'category': 'math', 'short_name': 'polar_to_cplx'},
 'python_generator': {'category': 'utility', 'short_name': ''},
 'realP_part': {'category': 'math', 'short_name': 'real_part'},
 'recombine_harmonic_indeces_cyclic': {'category': 'result',
                                       'short_name': 'recombine_harmonic_indeces_cyclic'},
 'rescope_fc': {'category': 'scoping', 'short_name': 'change_fc'},
 'rotate': {'category': 'geo', 'short_name': 'rotate'},
 'rotate_fc': {'category': 'geo', 'short_name': 'rotate_fc'},
 'scale': {'category': 'math', 'short_name': 'scale'},
 'scale_by_field': {'category': 'math',
                    'short_name': 'scale_by_field'},
 'scale_by_field_fc': {'category': 'math',
                       'short_name': 'scale_by_field_fc'},
 'scale_fc': {'category': 'math', 'short_name': 'scale_fc'},
 'scoping::by_property': {'category': 'scoping',
                          'short_name': 'splitted_on_property_type'},
 'scoping::connectivity_ids': {'category': 'scoping',
                               'short_name': 'connectivity_ids'},
 'scoping::intersect': {'category': 'scoping',
                        'short_name': 'intersect'},
 'scoping::on_coordinates': {'category': 'mapping',
                             'short_name': 'scoping_on_coordinates'},
 'scoping_provider_by_ns': {'category': 'scoping',
                            'short_name': 'on_named_selection'},
 'scoping_provider_by_prop': {'category': 'scoping',
                              'short_name': 'on_property'},
 'serializer': {'category': 'serialization',
                'short_name': 'serializer'},
 'sin': {'category': 'math', 'short_name': 'sin'},
 'sin_fc': {'category': 'math', 'short_name': 'sin_fc'},
 'solid_to_skin': {'category': 'mapping',
                   'short_name': 'solid_to_skin'},
 'split_fields': {'category': 'mesh', 'short_name': 'split_fields'},
 'split_mesh': {'category': 'mesh', 'short_name': 'split_mesh'},
 'sqr': {'category': 'math', 'short_name': 'sqr'},
 'sqr_fc': {'category': 'math', 'short_name': 'sqr_fc'},
 'sqrt': {'category': 'math', 'short_name': 'sqrt'},
 'sqrt_fc': {'category': 'math', 'short_name': 'sqrt_fc'},
 'stl_export': {'category': 'mesh', 'short_name': 'stl_export'},
 'strain_from_voigt': {'category': 'utility',
                       'short_name': 'strain_from_voigt'},
 'stream_provider': {'category': 'metadata',
                     'short_name': 'streams_provider'},
 'surfaces_provider': {'category': 'geo',
                       'short_name': 'elements_facets_surfaces_over_time'},
 'sweeping_phase': {'category': 'math',
                    'short_name': 'sweeping_phase'},
 'sweeping_phase_fc': {'category': 'math',
                       'short_name': 'sweeping_phase_fc'},
 'text_parser': {'category': 'utility',
                 'short_name': 'txt_file_to_dpf'},
 'thickness': {'category': 'result', 'short_name': 'thickness'},
 'time_of_max_by_entity': {'category': 'min_max',
                           'short_name': 'time_of_max_by_entity'},
 'time_of_min_by_entity': {'category': 'min_max',
                           'short_name': 'time_of_min_by_entity'},
 'to_elemental_fc': {'category': 'averaging',
                     'short_name': 'to_elemental_fc'},
 'to_nodal': {'category': 'averaging', 'short_name': 'to_nodal'},
 'to_nodal_fc': {'category': 'averaging',
                 'short_name': 'to_nodal_fc'},
 'topology::center_of_gravity': {'category': 'geo',
                                 'short_name': 'center_of_gravity'},
 'topology::mass': {'category': 'geo', 'short_name': 'mass'},
 'topology::moment_of_inertia': {'category': 'geo',
                                 'short_name': 'moment_of_inertia'},
 'torque': {'category': 'result', 'short_name': 'torque'},
 'transform_cylindricalCS': {'category': 'geo',
                             'short_name': 'rotate_in_cylindrical_cs'},
 'transform_cylindrical_cs_fc': {'category': 'geo',
                                 'short_name': 'rotate_in_cylindrical_cs_fc'},
 'transpose_scoping': {'category': 'scoping',
                       'short_name': 'transpose'},
 'unit_convert': {'category': 'math', 'short_name': 'unit_convert'},
 'unit_convert_fc': {'category': 'math',
                     'short_name': 'unit_convert_fc'},
 'volumes_provider': {'category': 'geo',
                      'short_name': 'elements_volumes_over_time'},
 'vtk::migrate_file': {'category': 'serialization',
                       'short_name': 'migrate_file_to_vtk'},
 'vtk::vtk::FieldProvider': {'category': 'serialization',
                             'short_name': 'vtk_to_fields'},
 'vtk_export': {'category': 'serialization',
                'short_name': 'vtk_export'}}