New-Item -Path ".\" -Name "test_launcher" -ItemType "directory"
New-Item -Path ".\" -Name "test_server" -ItemType "directory"
New-Item -Path ".\" -Name "test_local_server" -ItemType "directory"
New-Item -Path ".\" -Name "test_multi_server" -ItemType "directory"
New-Item -Path ".\" -Name "test_workflow" -ItemType "directory"
New-Item -Path ".\" -Name "test_remote_workflow" -ItemType "directory"
New-Item -Path ".\" -Name "test_remote_operator" -ItemType "directory"
New-Item -Path ".\" -Name "test_service" -ItemType "directory"
New-Item -Path ".\" -Name "test_custom_type_field" -ItemType "directory"
New-Item -Path ".\" -Name "test_cff" -ItemType "directory"
#New-Item -Path ".\" -Name "test_plugins" -ItemType "directory"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_launcher\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_server\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_local_server\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_multi_server\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_workflow\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_remote_workflow\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_remote_operator\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_service\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_custom_type_field\"
Copy-Item -Path "tests\conftest.py" -Destination ".\test_cff\"
#Copy-Item -Path "tests\conftest.py" -Destination ".\test_plugins\"
Copy-Item -Path "tests\test_launcher.py" -Destination ".\test_launcher\"
Copy-Item -Path "tests\test_server.py" -Destination ".\test_server\"
Copy-Item -Path "tests\test_local_server.py" -Destination ".\test_local_server\"
Copy-Item -Path "tests\test_multi_server.py" -Destination ".\test_multi_server\"
Copy-Item -Path "tests\test_workflow.py" -Destination ".\test_workflow\"
Copy-Item -Path "tests\test_remote_workflow.py" -Destination ".\test_remote_workflow\"
Copy-Item -Path "tests\test_remote_operator.py" -Destination ".\test_remote_operator\"
Copy-Item -Path "tests\test_service.py" -Destination ".\test_service\"
Copy-Item -Path "tests\test_custom_type_field.py" -Destination ".\test_custom_type_field\"
Copy-Item -Path "tests\test_cff.py" -Destination ".\test_cff\"
#Copy-Item -Path "tests\test_plugins.py" -Destination ".\test_plugins\"
Remove-Item -Path "tests\test_server.py"
Remove-Item -Path "tests\test_launcher.py"
Remove-Item -Path "tests\test_local_server.py"
Remove-Item -Path "tests\test_multi_server.py"
Remove-Item -Path "tests\test_workflow.py"
Remove-Item -Path "tests\test_remote_workflow.py"
Remove-Item -Path "tests\test_remote_operator.py"
Remove-Item -Path "tests\test_service.py"
Remove-Item -Path "tests\test_custom_type_field.py"
Remove-Item -Path "tests\test_cff.py"
#Remove-Item -Path "tests\test_plugins.py"