version: "3.9"
services:
  dpf-server:
    container_name: dpf-server
    build:
      context: .
      dockerfile: Dockerfile
      target: dpf_server
      args:
        # The base image of dpf-server container
        - DPF_SERVER_BASE_IMAGE=rockylinux:8.9-minimal
        # The version indicated in the standalone archive name (e.g: 24.2.pre0)
        - DPF_SERVER_VERSION=
    env_file:
      - dpf.env
    networks:
      - pydpfcore-nw

  pydpf-core:
    container_name: pydpf-core
    build:
      context: .
      dockerfile: Dockerfile
      target: devcontainer
      args:
        # The base image for devcontainer
        - DEVCONTAINER_VARIANT=3.10-bullseye
        # The user used inside of the container
        - USERNAME=vscode
    volumes:
      - ../:/pydpf-core:cached
      # Keeps your bash history
      - pydpfcore-bashhistory:/commandhistory
      # Keeps your python sites
      - pydpfcore-pythonsites:/home/vscode/.local/lib
    networks:
      - pydpfcore-nw

volumes:
  pydpfcore-bashhistory:
  pydpfcore-pythonsites:

networks:
  pydpfcore-nw:
    attachable: true