# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ansys.grpc.dpf.base_pb2 as base__pb2
import ansys.grpc.dpf.operator_config_pb2 as operator__config__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in operator_config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperatorConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/ansys.api.dpf.operator_config.v0.OperatorConfigService/Create',
                request_serializer=operator__config__pb2.CreateRequest.SerializeToString,
                response_deserializer=operator__config__pb2.OperatorConfig.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/ansys.api.dpf.operator_config.v0.OperatorConfigService/Update',
                request_serializer=operator__config__pb2.UpdateRequest.SerializeToString,
                response_deserializer=base__pb2.Empty.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/ansys.api.dpf.operator_config.v0.OperatorConfigService/List',
                request_serializer=operator__config__pb2.OperatorConfig.SerializeToString,
                response_deserializer=operator__config__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/ansys.api.dpf.operator_config.v0.OperatorConfigService/Delete',
                request_serializer=operator__config__pb2.OperatorConfig.SerializeToString,
                response_deserializer=base__pb2.Empty.FromString,
                _registered_method=True)


class OperatorConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperatorConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=operator__config__pb2.CreateRequest.FromString,
                    response_serializer=operator__config__pb2.OperatorConfig.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=operator__config__pb2.UpdateRequest.FromString,
                    response_serializer=base__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=operator__config__pb2.OperatorConfig.FromString,
                    response_serializer=operator__config__pb2.ListResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=operator__config__pb2.OperatorConfig.FromString,
                    response_serializer=base__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ansys.api.dpf.operator_config.v0.OperatorConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ansys.api.dpf.operator_config.v0.OperatorConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperatorConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ansys.api.dpf.operator_config.v0.OperatorConfigService/Create',
            operator__config__pb2.CreateRequest.SerializeToString,
            operator__config__pb2.OperatorConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ansys.api.dpf.operator_config.v0.OperatorConfigService/Update',
            operator__config__pb2.UpdateRequest.SerializeToString,
            base__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ansys.api.dpf.operator_config.v0.OperatorConfigService/List',
            operator__config__pb2.OperatorConfig.SerializeToString,
            operator__config__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ansys.api.dpf.operator_config.v0.OperatorConfigService/Delete',
            operator__config__pb2.OperatorConfig.SerializeToString,
            base__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
