# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: support_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ansys.grpc.dpf.support_pb2 as support__pb2
import ansys.grpc.dpf.time_freq_support_pb2 as time__freq__support__pb2
import ansys.grpc.dpf.meshed_region_pb2 as meshed__region__pb2
import ansys.grpc.dpf.cyclic_support_pb2 as cyclic__support__pb2
import ansys.grpc.dpf.field_pb2 as field__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15support_service.proto\x12 ansys.api.dpf.support_service.v0\x1a\rsupport.proto\x1a\x17time_freq_support.proto\x1a\x13meshed_region.proto\x1a\x14\x63yclic_support.proto\x1a\x0b\x66ield.proto\"\x82\x02\n\x0fSupportResponse\x12P\n\x11time_freq_support\x18\x01 \x01(\x0b\x32\x33.ansys.api.dpf.time_freq_support.v0.TimeFreqSupportH\x00\x12\x43\n\x0b\x64omain_mesh\x18\x02 \x01(\x0b\x32,.ansys.api.dpf.meshed_region.v0.MeshedRegionH\x00\x12H\n\x0e\x63yclic_support\x18\x03 \x01(\x0b\x32..ansys.api.dpf.cyclic_support.v0.CyclicSupportH\x00\x42\x0e\n\x0csupport_type\"\x98\x01\n\x0bListRequest\x12\x32\n\x07support\x18\x01 \x01(\x0b\x32!.ansys.api.dpf.support.v0.Support\x12\x17\n\x0fspecific_fields\x18\x02 \x03(\t\x12\x1c\n\x14specific_prop_fields\x18\x03 \x03(\t\x12\x1e\n\x16specific_string_fields\x18\x04 \x03(\t\"\xbe\x01\n\x0cListResponse\x12Y\n\x0e\x66ield_supports\x18\x01 \x03(\x0b\x32\x41.ansys.api.dpf.support_service.v0.ListResponse.FieldSupportsEntry\x1aS\n\x12\x46ieldSupportsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.ansys.api.dpf.field.v0.Field:\x02\x38\x01\x32\xdb\x01\n\x0eSupportService\x12\x62\n\nGetSupport\x12!.ansys.api.dpf.support.v0.Support\x1a\x31.ansys.api.dpf.support_service.v0.SupportResponse\x12\x65\n\x04List\x12-.ansys.api.dpf.support_service.v0.ListRequest\x1a..ansys.api.dpf.support_service.v0.ListResponseB\"\xaa\x02\x1f\x41nsys.Api.Dpf.SupportService.v0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'support_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\037Ansys.Api.Dpf.SupportService.v0'
  _globals['_LISTRESPONSE_FIELDSUPPORTSENTRY']._options = None
  _globals['_LISTRESPONSE_FIELDSUPPORTSENTRY']._serialized_options = b'8\001'
  _globals['_SUPPORTRESPONSE']._serialized_start=156
  _globals['_SUPPORTRESPONSE']._serialized_end=414
  _globals['_LISTREQUEST']._serialized_start=417
  _globals['_LISTREQUEST']._serialized_end=569
  _globals['_LISTRESPONSE']._serialized_start=572
  _globals['_LISTRESPONSE']._serialized_end=762
  _globals['_LISTRESPONSE_FIELDSUPPORTSENTRY']._serialized_start=679
  _globals['_LISTRESPONSE_FIELDSUPPORTSENTRY']._serialized_end=762
  _globals['_SUPPORTSERVICE']._serialized_start=765
  _globals['_SUPPORTSERVICE']._serialized_end=984
# @@protoc_insertion_point(module_scope)
