name: Ansys Lab

on:
# Can be called by the CI
  workflow_call:
    inputs:
      version:
        description: "Release version as 'vX.Y.Z'"
        type: string
        required: true
# Can be called manually
  workflow_dispatch:
    inputs:
      version:
        description: "Release version as 'vX.Y.Z'"
        type: string
        required: true

env:
  DESTINATION_BRANCH_NAME: ansys_lab_examples

jobs:
  deploy_examples:
    name: "Deploy examples for Ansys Lab"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.DESTINATION_BRANCH_NAME }}

      - name: "Clean-up working directory"
        shell: python
        run: |
          import glob
          import os
                    
          for example in glob.glob('**/*.ipynb', recursive=True):
            os.remove(example)
            print(f"Deleted {example}")

      - name: "Download Release Asset - HTML"
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          file: HTML-doc-ansys-dpf-core.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          version: tags/${{ inputs.version }}

      - name: "Extract ipynb examples"
        shell: python
        run: |
          import glob
          import os
          import shutil
          import zipfile
          with zipfile.ZipFile("HTML-doc-ansys-dpf-core.zip", 'r') as z:
            [z.extract(file, "./") for file in z.namelist() if file.endswith(".ipynb")]
          os.remove("HTML-doc-ansys-dpf-core.zip")
          
          if not "examples" in os.listdir(os.getcwd()):
            os.mkdir(os.path.join(os.getcwd(), "examples"))
          print(os.listdir(os.getcwd()))
          for folder in os.listdir(os.path.join(os.getcwd(), "_downloads")):
            print(os.listdir(os.path.join(os.path.join(os.getcwd(), "_downloads"), folder)))
          for example in glob.glob('**/*.ipynb', recursive=True):
            print(f"Moving {example}") 
            shutil.move(example, os.path.join(os.getcwd(), "examples"))
          print(os.listdir(os.path.join(os.getcwd(), "examples")))

      - name: "Push changes"
        shell: bash
        run: |
          git config --global user.name "pyansys-ci-bot"
          git add .
          git status
          git commit -a -m ${{ inputs.version }} || exit 0
          git push https://${{ secrets.PYANSYS_CI_BOT_TOKEN }}@github.com/ansys/pydpf-core.git --follow-tags
