name: CI Release

on:
  push:
    tags:
      - "v*"
  schedule:
    - cron: "0 13 * * 0"
  workflow_dispatch:
    inputs:
      ansys_version:
        description: "ANSYS version"
        required: false
        type: string
      standalone_branch_suffix:
        description: 'Suffix of the branch on standalone'
        required: false
        default: ''

#┌───────────── minute (0 - 59)
#│ ┌───────────── hour (0 - 23)
#│ │ ┌───────────── day of the month (1 - 31)
#│ │ │ ┌───────────── month (1 - 12)
#│ │ │ │ ┌───────────── day of the week (0 - 6), 0 being Sunday
#│ │ │ │ │
#│ │ │ │ │
#│ │ │ │ │
#* * * * *

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCUMENTATION_CNAME: 'dpf.docs.pyansys.com'

jobs:
  debug:
    name: "Debug"
    runs-on: ubuntu-latest
    steps:
    - name: Show the Github context for the triggered event
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

  style:
    name: "Style Check"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: ansys/actions/code-style@1f4f0896a8e49d3aec2f02ced215b04a32c85f28 # v10.2.7
        with:
          use-python-cache: false

  build_linux1:
    name: "Build linux1 wheel"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Install requirements"
        run: |
          pip install -U pip
          pip install --group build

      - name: "Build the manylinux1 wheel"
        shell: bash
        id: wheel
        run: |
          python .ci/build_wheel.py -p manylinux1
          cd dist
          export name=`ls ansys_dpf_core*.whl`
          echo ${name}
          echo "wheel_name=${name[0]}" >> $GITHUB_OUTPUT
          cd ..

      - name: "Upload wheel any as artifact"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ steps.wheel.outputs.wheel_name }}
          path: dist/${{ steps.wheel.outputs.wheel_name }}

  tests:
    name: "Test ${{ matrix.test_any && 'any' || 'platform-specific' }} wheel"
    permissions:
      contents: read # Required by tests.yml jobs
    uses: ./.github/workflows/tests.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - python_versions: '["3.10"]'
            wheel: true
            wheelhouse: true
            DOCSTRING: true
            test_any: false
          - python_versions: '["3.11", "3.12", "3.13", "3.14"]'
            wheel: false
            wheelhouse: true
            DOCSTRING: false
            test_any: false
          - python_versions: '["3.10"]'
            wheel: true
            wheelhouse: false
            DOCSTRING: false
            test_any: true
          - python_versions: '["3.11", "3.12", "3.13", "3.14"]'
            wheel: false
            wheelhouse: false
            DOCSTRING: false
            test_any: true
    with:
      ANSYS_VERSION: ${{ inputs.ansys_version || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).version }}
      python_versions: ${{ matrix.python_versions }}
      wheel: ${{ matrix.wheel }}
      wheelhouse: ${{ matrix.wheelhouse }}
      DOCSTRING: ${{ matrix.DOCSTRING }}
      test_any: ${{ matrix.test_any }}
      standalone_suffix: ${{ github.event.inputs.standalone_branch_suffix || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).patch }}
    secrets:
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    permissions:
      contents: read # Required by docs.yml jobs
      pull-requests: write # Required by doc-style job
    uses: ./.github/workflows/docs.yml
    with:
      ANSYS_VERSION: ${{ inputs.ansys_version || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).version }}
      standalone_suffix: ${{ github.event.inputs.standalone_branch_suffix || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).patch }}
      event_name: ${{ github.event_name }}
    secrets:
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  examples:
    permissions:
      contents: read # Required by examples.yml jobs
    uses: ./.github/workflows/examples.yml
    with:
      ANSYS_VERSION: ${{ inputs.ansys_version || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).version }}
      python_versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      standalone_suffix: ${{ github.event.inputs.standalone_branch_suffix || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).patch }}
    secrets:
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  tests-retro:
    name: "Test DPF ${{ matrix.version.version }}${{ matrix.version.patch }} compatibility"
    permissions:
      contents: read # Required by tests.yml jobs
    strategy:
      fail-fast: false
      matrix:
        version:
          - ${{ fromJson(vars.ANSYS_VERSIONS_RETRO_WITH_PATCH) }}
    uses: ./.github/workflows/tests.yml
    with:
      ANSYS_VERSION: ${{ matrix.version.version }}
      python_versions: '["3.10"]'
      DOCSTRING: false
      standalone_suffix: ${{ matrix.version.patch }}
    secrets:
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  tests-pydpf-post:
    name: "Test PyDPF-Post with ${{ matrix.version.version }}${{ matrix.version.patch }}"
    permissions:
      contents: read # Required by pydpf-post.yml jobs
      pull-requests: write # Required for posting test outcome comments
    strategy:
      fail-fast: false
      matrix:
        version:
          - ${{ fromJson(vars.ANSYS_VERSIONS_RETRO_WITH_PATCH) }}
        test_docstrings:
          - "false"
        include:
          - version: ${{ fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH) }}
            test_docstrings": "true"
    uses: ./.github/workflows/pydpf-post.yml
    with:
      ANSYS_VERSION: ${{ matrix.version.version }}
      standalone_suffix: ${{ matrix.version.patch }}
      test_docstrings: ${{ matrix.test_docstrings }}
      post_branch: latest
    secrets:
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  docker_tests:
    name: "Build and Test on Docker"
    permissions:
      contents: read # Required by test_docker.yml jobs
    uses: ./.github/workflows/test_docker.yml
    with:
      ANSYS_VERSION: ${{ inputs.ansys_version || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).version }}
      standalone_suffix: ${{ github.event.inputs.standalone_branch_suffix || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).patch }}
    secrets:
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docker_examples:
    name: "Run examples on Docker"
    permissions:
      contents: read # Required by examples_docker.yml jobs
    uses: ./.github/workflows/examples_docker.yml
    with:
      ANSYS_VERSION: ${{ inputs.ansys_version || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).version }}
      python_versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      standalone_suffix: ${{ github.event.inputs.standalone_branch_suffix || fromJson(vars.ANSYS_VERSION_LAST_RELEASED_WITH_PATCH).patch }}
    secrets:
      LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  draft_release:
    name: "Draft Release"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [style, tests, docs, examples, tests-retro, docker_tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0

      - name: "Display downloaded files"
        run: ls -R

      - name: "Create draft release"
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            ./**/*.whl
            ./**/*.zip
          draft: true
          generate_release_notes: true
