name: "Pull Request Labeler"
on:
  pull_request:
    types: [unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:

    # Label based on modified files
    - name: Label based on changed files
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: ''

    # Label based on branch name
    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'doc') || 
        startsWith(github.event.pull_request.head.ref, 'docs')
      with:
        labels: documentation

    # Label based on branch name
    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'example') || 
        startsWith(github.event.pull_request.head.ref, 'examples')
      with:
        labels: examples

    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'docker') ||
        startsWith(github.event.pull_request.head.ref, 'no-ci') ||
        startsWith(github.event.pull_request.head.ref, 'ci')
      with:
        labels: CI/CD

    - uses: actions-ecosystem/action-add-labels@v1
      if: startsWith(github.event.pull_request.head.ref, 'maint')
      with:
        labels: maintenance

    - uses: actions-ecosystem/action-add-labels@v1
      if: startsWith(github.event.pull_request.head.ref, 'feat')
      with:
        labels: |
          enhancement

    - uses: actions-ecosystem/action-add-labels@v1
      if: |
        startsWith(github.event.pull_request.head.ref, 'fix') ||
        startsWith(github.event.pull_request.head.ref, 'patch')
      with:
        labels: bug

  commenter:
    runs-on: ubuntu-latest
    needs: labeler
    steps:
    - name: Suggest to add labels
      uses: peter-evans/create-or-update-comment@v2
      # Execute only when no labels have been applied to the pull request
      if: toJSON(github.event.pull_request.labels.*.name) == '[]'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Please add one of the following labels to add this contribution to the Release Notes :point_down:
          - [bug](https://github.com/ansys/pydpf-core/pulls?q=label%3Abug+)
          - [enhancement](https://github.com/ansys/pydpf-core/pulls?q=label%3Aenhancement+)
          - [documentation](https://github.com/ansys/pydpf-core/pulls?q=label%3Adocumentation+)
          - [examples](https://github.com/ansys/pydpf-core/pulls?q=label%3Aexamples+)
          - [maintenance](https://github.com/ansys/pydpf-core/pulls?q=label%3Amaintenance+)
          - [CI/CD](https://github.com/ansys/pydpf-core/pulls?q=label%3Aci%2Fcd+)