name: Nightly Documentation Build

on:
  workflow_dispatch:
  schedule:  # UTC at 0400
    - cron:  '0 4 * * *'

env:
  DOCUMENTATION_CNAME: 'dpf.docs.pyansys.com'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs: 
  docs:
    uses: ./.github/workflows/docs.yml
    with:
      ANSYS_VERSION: "241"
      standalone_suffix: ${{ github.event.inputs.standalone_branch_suffix || '' }}
      custom-requirements: ${{ github.event.inputs.custom-requirements || 'requirements/requirements_dev.txt' }}
      custom-wheels: ${{ github.event.inputs.custom-wheels || './dpf-standalone/v241/dist' }}
      event_name: ${{ github.event_name }}
    secrets: inherit

  upload-development-docs:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [docs]
    steps:
      - name: "Upload development documentation"
        uses: ansys/actions/doc-deploy-dev@v4
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          doc-artifact-name: HTML-doc-ansys-dpf-core.zip
          decompress-artifact: true