name: test_docker

on:
# Can be called by the CI
  workflow_call:
    inputs:
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''
      ANSYS_VERSION:
        required: false
        type: string
    secrets:
      LICENSE_SERVER:
        required: true
      PYANSYS_CI_BOT_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: false
# Can be called manually
  workflow_dispatch:
    inputs:
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''
      ANSYS_VERSION:
        description: "ANSYS version to run."
        required: false
        type: string

env:
  PACKAGE_NAME: ansys-dpf-core
  MODULE: core
  ANSYS_DPF_ACCEPT_LA: Y
  ANSYSLMD_LICENSE_FILE: 1055@${{secrets.LICENSE_SERVER}}

permissions: {}

jobs:
  docker_tests:
    name: "Build and Test On Docker"
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: ["ubuntu-latest"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Setup Python"
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Setup Graphviz"
        uses: ts-graphviz/setup-graphviz@b1de5da23ed0a6d14e0aeee8ed52fdd87af2363c # v2.0.2

      - name: "Install requirements"
        run: |
          pip install -U pip
          pip install --group build

      - name: "Build the wheel"
        shell: bash
        env:
          MATRIX_OS: ${{ matrix.os }}
        run: |
          if [ "${MATRIX_OS}" == "ubuntu-latest" ]; then
              export platform="manylinux_2_17"
          else
              export platform="win"
          fi
          python .ci/build_wheel.py -p $platform -w

      - name: "Expose the wheel"
        shell: bash
        id: wheel
        working-directory: dist
        run: |
          export name=`ls ansys_dpf_core*.whl`
          echo ${name}
          echo "wheel_name=${name[0]}" >> $GITHUB_OUTPUT

      - name: "Install package wheel"
        shell: bash
        env:
          WHEEL_NAME: ${{ steps.wheel.outputs.wheel_name }}
        run: |
          pip install dist/${WHEEL_NAME}[graphics]

      - name: "Install DPF"
        id: set-server-path
        uses: ansys/pydpf-actions/install-dpf-docker@v2.3
        with:
          dpf-standalone-TOKEN: ${{secrets.PYANSYS_CI_BOT_TOKEN}}
          standalone_suffix: ${{ inputs.standalone_suffix }}
          ANSYS_VERSION : ${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}

      - name: "Check licences of packages"
        uses: ansys/pydpf-actions/check-licenses@v2.3

      - name: "Test import"
        shell: bash
        working-directory: tests
        run: python -c "from ansys.dpf import core"

      - name: "Prepare Testing Environment"
        uses: ansys/pydpf-actions/prepare_tests@v2.3
        with:
          DEBUG: true
          install-from-dependency-groups: "true"

      - name: "List installed packages"
        shell: bash
        run: pip list

      - name: "Separate long Core tests"
        shell: pwsh
        run: |
          .github\workflows\scripts\separate_long_core_tests.ps1

      - name: "Set pytest arguments"
        shell: bash
        run: |
          echo "COVERAGE=--cov=ansys.dpf.${MODULE} --cov-report=xml --cov-report=html --log-level=ERROR --cov-append" >> $GITHUB_ENV
          echo "RERUNS=--reruns 2 --reruns-delay 1" >> $GITHUB_ENV

          echo "DPF_DEFAULT_GRPC_MODE=insecure" >> $GITHUB_ENV

      - name: "Test API"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 10
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results.xml tests/.

      - name: "Test API test_launcher"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 2
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results2.xml test_launcher/.

      - name: "Test API test_server"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 8
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results3.xml test_server/.

      - name: "Test API test_local_server"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 2
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results4.xml test_local_server/.

      - name: "Test API test_multi_server"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 5
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results5.xml test_multi_server/.

      - name: "Test API test_remote_workflow"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 2
          max_attempts: 3
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results6.xml test_remote_workflow/.

      - name: "Test API test_remote_operator"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 2
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results7.xml test_remote_operator/.

      - name: "Test API test_workflow"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 3
          max_attempts: 3
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results8.xml test_workflow/.

      - name: "Test API test_service"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 3
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=tests/junit/test-results9.xml test_service/.

      - name: "Test Operators"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 3
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=../tests/junit/test-results12.xml tests/operators/.

      - name: "Test Documentation"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_minutes: 8
          max_attempts: 2
          shell: bash
          command: |
            pytest $DEBUG $COVERAGE $RERUNS --junitxml=../tests/junit/test-results13.xml test_documentation/.

#      - name: "Test API Entry"
#        shell: bash
#        working-directory: tests
#        run: |
#          cd entry
#          pytest $DEBUG $COVERAGE $RERUNS --junitxml=junit/test-results10.xml  .
#        if: always()
#        timeout-minutes: 10

      - name: "Upload Test Results"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.PACKAGE_NAME }}_${{ matrix.python-version }}_${{ matrix.os }}_pytest_${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}_docker
          path: tests/junit/test-results.xml
        timeout-minutes: 5

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          report_type: coverage
          name: ${{ env.PACKAGE_NAME }}_${{ matrix.python-version }}_${{ matrix.os }}_pytest_${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}_docker.xml
          flags: docker,${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }},${{ matrix.os }},${{ matrix.python-version }}

      - name: "Upload test analytics results to Codecov"
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          name: test_results_${{ env.PACKAGE_NAME }}_${{ matrix.python-version }}_${{ matrix.os }}_${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}${{ inputs.test_any == 'true' && '_any' || '' }}
          flags: ${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }},${{ matrix.os }},${{ matrix.python-version }}${{ inputs.test_any == 'true' && ',any' || '' }}
