name: tests # zizmor: ignore[concurrency-limits] , this is a reusable workflow

on:
# Can be called by the CI
  workflow_call:
    inputs:
      python_versions:
        required: false
        type: string
        default: '["3.10"]'
      ANSYS_VERSION:
        required: false
        type: string
      wheel:
        required: false
        type: string
        default: 'false'
      wheelhouse:
        required: false
        type: string
        default: 'false'
      DOCSTRING:
        required: false
        type: string
        default: 'true'
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''
      test_any:
        description: "Test the any version of the wheel"
        required: false
        type: string
        default: 'false'
    secrets:
      LICENSE_SERVER:
        required: true
      PYANSYS_CI_BOT_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: false
# Can be called manually
  workflow_dispatch:
    inputs:
      python_versions:
        description: "Python interpreters to test."
        required: true
        type: string
        default: '["3.10", "3.11", "3.12"]'
      ANSYS_VERSION:
        description: "ANSYS version"
        required: false
        type: string
      wheel:
        description: "Generate a wheel"
        required: false
        type: string
        default: 'false'
      wheelhouse:
        description: "Generate a wheelhouse"
        required: false
        type: string
        default: 'false'
      DOCSTRING:
        description: "Whether to test docstrings"
        required: false
        type: string
        default: 'true'
      standalone_suffix:
        description: "Suffix of the branch on standalone"
        required: false
        type: string
        default: ''
      test_any:
        description: "Test the any version of the wheel"
        required: false
        type: string
        default: 'false'

env:
  PACKAGE_NAME: ansys-dpf-core
  MODULE: core

permissions: {}

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.set_array.outputs.python_versions }}
    steps:
      - id: set_array
        env:
          PYTHON_VERSIONS: ${{ inputs.python_versions }}
        run: |
          echo "python_versions=${PYTHON_VERSIONS}" >> $GITHUB_OUTPUT

  tests:
    name: "Tests"
    needs: setup
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(needs.setup.outputs.python_versions) }}
        os: ["windows-latest", "ubuntu-latest"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Set licensing if necessary"
        if: ${{ (inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT) > '231' }}
        shell: bash
        env:
          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
        run: |
          echo "ANSYS_DPF_ACCEPT_LA=Y" >> $GITHUB_ENV
          echo "ANSYSLMD_LICENSE_FILE=1055@${LICENSE_SERVER}" >> $GITHUB_ENV

      - name: "Setup Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Setup Graphviz"
        uses: ts-graphviz/setup-graphviz@b1de5da23ed0a6d14e0aeee8ed52fdd87af2363c # v2.0.2

      - name: "Update pip to the latest version and install tox"
        shell: pwsh
        run: |
          python -m pip install -U pip
          python -m pip install -U tox tox-uv

      - name: "Build the wheel"
        shell: bash
        env:
          TEST_ANY: ${{ inputs.test_any }}
          MATRIX_OS: ${{ matrix.os }}
        run: |
          if [ "${TEST_ANY}" == 'true' ]; then
              export platform="any"
          elif [ "${MATRIX_OS}" == "ubuntu-latest" ]; then
              export platform="manylinux_2_17"
          else
              export platform="win"
          fi
          tox -e build-wheel -- $platform

      - name: "Expose the wheel"
        shell: bash
        id: wheel
        working-directory: dist
        run: |
          export name=`ls ansys_dpf_core*.whl`
          echo ${name}
          echo "wheel_name=${name[0]}" >> $GITHUB_OUTPUT

      - name: "Upload wheel to artifacts"
        if: (inputs.wheel == 'true') && !( (inputs.test_any == 'true') && (matrix.os == 'ubuntu-latest') )
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ steps.wheel.outputs.wheel_name }}
          path: dist/${{ steps.wheel.outputs.wheel_name }}

      - name: "Define wheelhouse name"
        if: inputs.wheelhouse == 'true'
        shell: bash
        id: wheelhouse
        env:
          WHEEL_NAME: ${{ steps.wheel.outputs.wheel_name }}
          RUNNER_OS: ${{ runner.os }}
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          export wheel_name=${WHEEL_NAME}
          export IFS='-'
          read -a strarr <<< $wheel_name
          export version="${strarr[1]}"
          echo $version
          export name=ansys-dpf-core-v${version}-wheelhouse-${RUNNER_OS}-${PYTHON_VERSION}.zip
          echo "name=${name}" >> "$GITHUB_OUTPUT"

      - name: "Zip wheelhouse"
        if: inputs.wheelhouse == 'true'
        uses: vimtor/action-zip@1379ea20d4c5705669ba81fd626dd01b1c738f26 # v1.2
        with:
          files: dist
          dest: ${{ steps.wheelhouse.outputs.name }}

      - name: "Upload wheelhouse to artifacts"
        if: inputs.wheelhouse == 'true'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ steps.wheelhouse.outputs.name }}
          path: ${{ steps.wheelhouse.outputs.name }}
          retention-days: 7

      - name: "Install DPF"
        id: set-server-path
        uses: ansys/pydpf-actions/install-dpf-server@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        with:
          dpf-standalone-TOKEN: ${{secrets.PYANSYS_CI_BOT_TOKEN}}
          standalone_suffix: ${{ inputs.standalone_suffix }}
          ANSYS_VERSION : ${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}

      - name: "Check licences of packages"
        uses: ansys/pydpf-actions/check-licenses@195207a462b23da5645fde44ac685e81b29035a4 # v2.3

      - name: "Test import"
        shell: bash
        env:
          WHEEL_NAME: ${{ steps.wheel.outputs.wheel_name }}
        run: |
          python -m pip install dist/${WHEEL_NAME}
          python -c "from ansys.dpf import core"

      - name: "Prepare Testing Environment"
        uses: ansys/pydpf-actions/prepare_tests@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        with:
          DEBUG: true
          install-from-dependency-groups: "true"

      - name: "Test Docstrings"
        if: (inputs.DOCSTRING == 'true')
        uses: ansys/pydpf-actions/test_docstrings@195207a462b23da5645fde44ac685e81b29035a4 # v2.3
        with:
          MODULE: ${{env.MODULE}}
          PACKAGE_NAME: ${{env.PACKAGE_NAME}}_${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}${{ inputs.standalone_suffix }}
          working-directory: src

      - name: "Set tox extra CLI arguments"
        id: tox-cli-arguments
        shell: bash
        env:
          WHEEL_NAME: ${{ steps.wheel.outputs.wheel_name }}
          ANSYS_VERSION_INPUT: ${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}
        run: |
          if [ "$MODE" = "PIP" ]; then
            echo "TOX_INSTALLPKG=dist/${WHEEL_NAME}" >> "$GITHUB_OUTPUT"
            echo "TOX_XARG=testenv.deps+=-e dpf-standalone/v${ANSYS_VERSION_INPUT}" >> "$GITHUB_OUTPUT"
          else
            echo "TOX_INSTALLPKG=dist/${WHEEL_NAME}" >> "$GITHUB_OUTPUT"
          fi

      - name: "Organize test files"
        shell: bash
        run: |
          tox -e pretest

      - name: "Test API test_entry"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          TOX_INSTALLPKG: ${{ steps.tox-cli-arguments.outputs.TOX_INSTALLPKG }}
          TOX_XARG: ${{ steps.tox-cli-arguments.outputs.TOX_XARG }}
        with:
          timeout_minutes: 10
          max_attempts: 2
          shell: bash
          command: |
            export DPF_DEFAULT_GRPC_MODE=insecure
            tox --installpkg "$TOX_INSTALLPKG" ${TOX_XARG:+-x "$TOX_XARG"} -e test-api_entry,kill-servers

      - name: "Run compatible tests in parallel"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          TOX_INSTALLPKG: ${{ steps.tox-cli-arguments.outputs.TOX_INSTALLPKG }}
          TOX_XARG: ${{ steps.tox-cli-arguments.outputs.TOX_XARG }}
        with:
          timeout_minutes: 20
          max_attempts: 2
          shell: bash
          command: |
            export DPF_DEFAULT_GRPC_MODE=insecure
            tox run-parallel --installpkg "$TOX_INSTALLPKG" ${TOX_XARG:+-x "$TOX_XARG"} -m ciparalleltests

      - name: "Test API test_server"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          TOX_INSTALLPKG: ${{ steps.tox-cli-arguments.outputs.TOX_INSTALLPKG }}
          TOX_XARG: ${{ steps.tox-cli-arguments.outputs.TOX_XARG }}
        with:
          timeout_minutes: 10
          max_attempts: 2
          shell: bash
          command: |
            export DPF_DEFAULT_GRPC_MODE=insecure
            tox --installpkg "$TOX_INSTALLPKG" ${TOX_XARG:+-x "$TOX_XARG"} -e test-server,kill-servers

      - name: "Test API test_remote_workflow"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          TOX_INSTALLPKG: ${{ steps.tox-cli-arguments.outputs.TOX_INSTALLPKG }}
          TOX_XARG: ${{ steps.tox-cli-arguments.outputs.TOX_XARG }}
        with:
          timeout_minutes: 10
          max_attempts: 3
          shell: bash
          command: |
            export DPF_DEFAULT_GRPC_MODE=insecure
            tox --installpkg "$TOX_INSTALLPKG" ${TOX_XARG:+-x "$TOX_XARG"} -e test-remote_workflow,kill-servers

      - name: "Test API test_remote_operator"
        shell: bash
        env:
          TOX_INSTALLPKG: ${{ steps.tox-cli-arguments.outputs.TOX_INSTALLPKG }}
          TOX_XARG: ${{ steps.tox-cli-arguments.outputs.TOX_XARG }}
        run: |
          export DPF_DEFAULT_GRPC_MODE=insecure
          tox --installpkg "$TOX_INSTALLPKG" ${TOX_XARG:+-x "$TOX_XARG"} -e test-remote_operator,kill-servers

      - name: "Test API test_workflow"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          TOX_INSTALLPKG: ${{ steps.tox-cli-arguments.outputs.TOX_INSTALLPKG }}
          TOX_XARG: ${{ steps.tox-cli-arguments.outputs.TOX_XARG }}
        with:
          timeout_minutes: 10
          max_attempts: 4
          shell: bash
          command: |
            export DPF_DEFAULT_GRPC_MODE=insecure
            tox --installpkg "$TOX_INSTALLPKG" ${TOX_XARG:+-x "$TOX_XARG"} -e test-workflow,kill-servers

      - name: "Test API test_service"
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        env:
          TOX_INSTALLPKG: ${{ steps.tox-cli-arguments.outputs.TOX_INSTALLPKG }}
          TOX_XARG: ${{ steps.tox-cli-arguments.outputs.TOX_XARG }}
        with:
          timeout_minutes: 10
          max_attempts: 2
          shell: bash
          command: |
            export DPF_DEFAULT_GRPC_MODE=insecure
            tox --installpkg "$TOX_INSTALLPKG" ${TOX_XARG:+-x "$TOX_XARG"} -e test-service,kill-servers

      - name: "Combine coverage results"
        shell: bash
        run: |
          tox -e covreport

      - name: "Upload Test Results"
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ env.PACKAGE_NAME }}_${{ matrix.python-version }}_${{ matrix.os }}_pytest_${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}${{ inputs.test_any == 'true' && '_any' || '' }}
          path: tests/junit/test-results.xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          report_type: coverage
          files: ./.tox/.cov/coverage.xml
          name: ${{ env.PACKAGE_NAME }}_${{ matrix.python-version }}_${{ matrix.os }}_pytest_${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}${{ inputs.test_any == 'true' && '_any' || '' }}.xml
          flags: ${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }},${{ matrix.os }},${{ matrix.python-version }}${{ inputs.test_any == 'true' && ',any' || '' }}

      - name: "Upload test analytics results to Codecov"
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          name: test_results_${{ env.PACKAGE_NAME }}_${{ matrix.python-version }}_${{ matrix.os }}_${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }}${{ inputs.test_any == 'true' && '_any' || '' }}
          flags: ${{ inputs.ANSYS_VERSION || vars.ANSYS_VERSION_DEFAULT }},${{ matrix.os }},${{ matrix.python-version }}${{ inputs.test_any == 'true' && ',any' || '' }}
